<?php

return [
    'acl' => [
        'leads'           => 'Leads',
        'lead'            => 'Lead',
        'quotes'          => 'Cotações',
        'mail'            => 'E-mail',
        'inbox'           => 'Caixa de Entrada',
        'draft'           => 'Rascunho',
        'outbox'          => 'Caixa de Saída',
        'sent'            => 'Enviados',
        'trash'           => 'Lixeira',
        'activities'      => 'Atividades',
        'webhook'         => 'Webhook',
        'contacts'        => 'Contatos',
        'persons'         => 'Pessoas',
        'organizations'   => 'Organizações',
        'products'        => 'Produtos',
        'settings'        => 'Configurações',
        'groups'          => 'Grupos',
        'roles'           => 'Funções',
        'users'           => 'Usuários',
        'user'            => 'Usuário',
        'automation'      => 'Automação',
        'attributes'      => 'Atributos',
        'pipelines'       => 'Funis',
        'sources'         => 'Fontes',
        'types'           => 'Tipos',
        'email-templates' => 'Modelos de E-mail',
        'workflows'       => 'Fluxos de Trabalho',
        'other-settings'  => 'Outras Configurações',
        'tags'            => 'Tags',
        'configuration'   => 'Configuração',
        'create'          => 'Criar',
        'edit'            => 'Editar',
        'view'            => 'Visualizar',
        'print'           => 'Imprimir',
        'delete'          => 'Excluir',
        'export'          => 'Exportar',
        'mass-delete'     => 'Exclusão em Massa',
    ],

    'users' => [
        'activate-warning' => 'Sua conta ainda não está ativada. Por favor, entre em contato com o administrador.',
        'login-error'      => 'As credenciais não correspondem aos nossos registros.',

        'login' => [
            'email'                => 'Endereço de E-mail',
            'forget-password-link' => 'Esqueceu a Senha?',
            'password'             => 'Senha',
            'submit-btn'           => 'Entrar',
            'title'                => 'Entrar',
        ],

        'forget-password' => [
            'create' => [
                'email'           => 'E-mail Registrado',
                'email-not-exist' => 'E-mail Não Existe',
                'page-title'      => 'Esqueceu a Senha',
                'reset-link-sent' => 'Link de redefinição de senha enviado',
                'sign-in-link'    => 'Voltar para Login?',
                'submit-btn'      => 'Redefinir',
                'title'           => 'Recuperar Senha',
            ],
        ],

        'reset-password' => [
            'back-link-title'  => 'Voltar para Login?',
            'confirm-password' => 'Confirmar Senha',
            'email'            => 'E-mail Registrado',
            'password'         => 'Senha',
            'submit-btn'       => 'Redefinir Senha',
            'title'            => 'Redefinir Senha',
        ],
    ],

    'account' => [
        'edit' => [
            'back-btn'          => 'Voltar',
            'change-password'   => 'Alterar Senha',
            'confirm-password'  => 'Confirmar Senha',
            'current-password'  => 'Senha Atual',
            'email'             => 'E-mail',
            'general'           => 'Geral',
            'invalid-password'  => 'A senha atual que você digitou está incorreta.',
            'name'              => 'Nome',
            'password'          => 'Senha',
            'profile-image'     => 'Imagem do Perfil',
            'save-btn'          => 'Salvar Conta',
            'title'             => 'Minha Conta',
            'update-success'    => 'Conta atualizada com sucesso',
            'upload-image-info' => 'Envie uma Imagem de Perfil (110px X 110px) em formato PNG ou JPG',
        ],
    ],

    'components' => [
        'activities' => [
            'actions' => [
                'mail' => [
                    'btn'          => 'E-mail',
                    'title'        => 'Compor E-mail',
                    'to'           => 'Para',
                    'enter-emails' => 'Pressione enter para adicionar e-mails',
                    'cc'           => 'CC',
                    'bcc'          => 'CCO',
                    'subject'      => 'Assunto',
                    'send-btn'     => 'Enviar',
                    'message'      => 'Mensagem',
                ],

                'file' => [
                    'btn'           => 'Arquivo',
                    'title'         => 'Adicionar Arquivo',
                    'title-control' => 'Título',
                    'name'          => 'Nome',
                    'description'   => 'Descrição',
                    'file'          => 'Arquivo',
                    'save-btn'      => 'Salvar Arquivo',
                ],

                'note' => [
                    'btn'      => 'Nota',
                    'title'    => 'Adicionar Nota',
                    'comment'  => 'Comentário',
                    'save-btn' => 'Salvar Nota',
                ],

                'activity' => [
                    'btn'           => 'Atividade',
                    'title'         => 'Adicionar Atividade',
                    'title-control' => 'Título',
                    'description'   => 'Descrição',
                    'schedule-from' => 'Agendar De',
                    'schedule-to'   => 'Agendar Até',
                    'location'      => 'Localização',
                    'call'          => 'Ligação',
                    'meeting'       => 'Reunião',
                    'lunch'         => 'Almoço',
                    'save-btn'      => 'Salvar Atividade',

                    'participants' => [
                        'title'       => 'Participantes',
                        'placeholder' => 'Digite para pesquisar participantes',
                        'users'       => 'Usuários',
                        'persons'     => 'Pessoas',
                        'no-results'  => 'Nenhum resultado encontrado...',
                    ],
                ],
            ],

            'index' => [
                'from'         => 'De',
                'to'           => 'Para',
                'cc'           => 'Cc',
                'bcc'          => 'Cco',
                'all'          => 'Todos',
                'planned'      => 'Planejados',
                'calls'        => 'Ligações',
                'meetings'     => 'Reuniões',
                'lunches'      => 'Almoços',
                'files'        => 'Arquivos',
                'quotes'       => 'Cotações',
                'notes'        => 'Notas',
                'emails'       => 'E-mails',
                'change-log'   => 'Registros de Alteração',
                'by-user'      => 'Por :user',
                'scheduled-on' => 'Agendado para',
                'location'     => 'Localização',
                'participants' => 'Participantes',
                'mark-as-done' => 'Marcar como Concluído',
                'delete'       => 'Excluir',
                'edit'         => 'Editar',
                'view'         => 'Visualizar',
                'unlink'       => 'Desvincular',
                'empty'        => 'Vazio',

                'empty-placeholders' => [
                    'all' => [
                        'title'       => 'Nenhuma Atividade Encontrada',
                        'description' => 'Nenhuma atividade encontrada para isto. Você pode adicionar atividades clicando no botão no painel esquerdo.',
                    ],

                    'planned' => [
                        'title'       => 'Nenhuma Atividade Planejada Encontrada',
                        'description' => 'Nenhuma atividade planejada encontrada para isto. Você pode adicionar atividades planejadas clicando no botão no painel esquerdo.',
                    ],

                    'notes' => [
                        'title'       => 'Nenhuma Nota Encontrada',
                        'description' => 'Nenhuma nota encontrada para isto. Você pode adicionar notas clicando no botão no painel esquerdo.',
                    ],

                    'calls' => [
                        'title'       => 'Nenhuma Ligação Encontrada',
                        'description' => 'Nenhuma ligação encontrada para isto. Você pode adicionar ligações clicando no botão no painel esquerdo.',
                    ],

                    'meetings' => [
                        'title'       => 'Nenhuma Reunião Encontrada',
                        'description' => 'Nenhuma reunião encontrada para isto. Você pode adicionar reuniões clicando no botão no painel esquerdo.',
                    ],

                    'lunches' => [
                        'title'       => 'Nenhum Almoço Encontrado',
                        'description' => 'Nenhum almoço encontrado para isto. Você pode adicionar almoços clicando no botão no painel esquerdo.',
                    ],

                    'files' => [
                        'title'       => 'Nenhum Arquivo Encontrado',
                        'description' => 'Nenhum arquivo encontrado para isto. Você pode adicionar arquivos clicando no botão no painel esquerdo.',
                    ],

                    'emails' => [
                        'title'       => 'Nenhum E-mail Encontrado',
                        'description' => 'Nenhum e-mail encontrado para isto. Você pode adicionar e-mails clicando no botão no painel esquerdo.',
                    ],

                    'system' => [
                        'title'       => 'Nenhum Registro de Alteração Encontrado',
                        'description' => 'Nenhum registro de alteração encontrado para isto.',
                    ],
                ],
            ],
        ],

        'media' => [
            'images' => [
                'add-image-btn'     => 'Adicionar Imagem',
                'ai-add-image-btn'  => 'IA Mágica',
                'allowed-types'     => 'png, jpeg, jpg',
                'not-allowed-error' => 'Apenas arquivos de imagem (.jpeg, .jpg, .png, ..) são permitidos.',

                'placeholders' => [
                    'front'     => 'Frente',
                    'next'      => 'Próximo',
                    'size'      => 'Tamanho',
                    'use-cases' => 'Casos de Uso',
                    'zoom'      => 'Zoom',
                ],
            ],

            'videos' => [
                'add-video-btn'     => 'Adicionar Vídeo',
                'allowed-types'     => 'mp4, webm, mkv',
                'not-allowed-error' => 'Apenas arquivos de vídeo (.mp4, .mov, .ogg ..) são permitidos.',
            ],
        ],

        'datagrid' => [
            'index' => [
                'no-records-selected'              => 'Nenhum registro foi selecionado.',
                'must-select-a-mass-action-option' => 'Você deve selecionar uma opção de ação em massa.',
                'must-select-a-mass-action'        => 'Você deve selecionar uma ação em massa.',
            ],

            'toolbar' => [
                'length-of' => ':length de',
                'of'        => 'de',
                'per-page'  => 'Por Página',
                'results'   => ':total Resultados',
                'delete'    => 'Excluir',
                'selected'  => ':total Itens Selecionados',

                'mass-actions' => [
                    'submit'        => 'Enviar',
                    'select-option' => 'Selecionar Opção',
                    'select-action' => 'Selecionar Ação',
                ],

                'filter' => [
                    'apply-filters-btn' => 'Aplicar Filtros',
                    'back-btn'          => 'Voltar',
                    'create-new-filter' => 'Criar Novo Filtro',
                    'custom-filters'    => 'Filtros Personalizados',
                    'delete-error'      => 'Algo deu errado ao excluir o filtro, por favor tente novamente.',
                    'delete-success'    => 'Filtro foi excluído com sucesso.',
                    'empty-description' => 'Não há filtros selecionados disponíveis para salvar. Por favor, selecione filtros para salvar.',
                    'empty-title'       => 'Adicionar Filtros para Salvar',
                    'name'              => 'Nome',
                    'quick-filters'     => 'Filtros Rápidos',
                    'save-btn'          => 'Salvar',
                    'save-filter'       => 'Salvar Filtro',
                    'saved-success'     => 'Filtro foi salvo com sucesso.',
                    'selected-filters'  => 'Filtros Selecionados',
                    'title'             => 'Filtro',
                    'update'            => 'Atualizar',
                    'update-filter'     => 'Atualizar Filtro',
                    'updated-success'   => 'Filtro foi atualizado com sucesso.',
                ],

                'search' => [
                    'title' => 'Pesquisar',
                ],
            ],

            'filters' => [
                'select' => 'Selecionar',
                'title'  => 'Filtros',

                'dropdown' => [
                    'searchable' => [
                        'at-least-two-chars' => 'Digite pelo menos 2 caracteres...',
                        'no-results'         => 'Nenhum resultado encontrado...',
                    ],
                ],

                'custom-filters' => [
                    'clear-all' => 'Limpar Tudo',
                    'title'     => 'Filtros Personalizados',
                ],

                'boolean-options' => [
                    'false' => 'Falso',
                    'true'  => 'Verdadeiro',
                ],

                'date-options' => [
                    'last-month'        => 'Mês Passado',
                    'last-six-months'   => 'Últimos 6 Meses',
                    'last-three-months' => 'Últimos 3 Meses',
                    'this-month'        => 'Este Mês',
                    'this-week'         => 'Esta Semana',
                    'this-year'         => 'Este Ano',
                    'today'             => 'Hoje',
                    'yesterday'         => 'Ontem',
                ],
            ],

            'table' => [
                'actions'              => 'Ações',
                'no-records-available' => 'Nenhum Registro Disponível.',
            ],
        ],

        'modal' => [
            'confirm' => [
                'agree-btn'    => 'Concordar',
                'disagree-btn' => 'Discordar',
                'message'      => 'Tem certeza que deseja realizar esta ação?',
                'title'        => 'Tem certeza?',
            ],
        ],

        'tags' => [
            'index' => [
                'title'          => 'Tags',
                'added-tags'     => 'Tags Adicionadas',
                'save-btn'       => 'Salvar Tag',
                'placeholder'    => 'Digite para pesquisar tags',
                'add-tag'        => 'Adicionar \":term\"...',
                'aquarelle-red'  => 'Vermelho Aquarela',
                'crushed-cashew' => 'Castanha Triturada',
                'beeswax'        => 'Cera de Abelha',
                'lemon-chiffon'  => 'Chiffon Limão',
                'snow-flurry'    => 'Nevasca',
                'honeydew'       => 'Melão',
            ],
        ],

        'layouts' => [
            'header' => [
                'mega-search' => [
                    'title'   => 'Pesquisar',

                    'tabs' => [
                        'leads'    => 'Leads',
                        'quotes'   => 'Cotações',
                        'persons'  => 'Pessoas',
                        'products' => 'Produtos',
                    ],

                    'explore-all-products'          => 'Explorar todos os Produtos',
                    'explore-all-leads'             => 'Explorar todos os Leads',
                    'explore-all-contacts'          => 'Explorar todos os Contatos',
                    'explore-all-quotes'            => 'Explorar todas as Cotações',
                    'explore-all-matching-products' => 'Explorar todos os produtos correspondentes a ":query" (:count)',
                    'explore-all-matching-leads'    => 'Explorar todos os leads correspondentes a ":query" (:count)',
                    'explore-all-matching-contacts' => 'Explorar todos os contatos correspondentes a ":query" (:count)',
                    'explore-all-matching-quotes'   => 'Explorar todas as cotações correspondentes a ":query" (:count)',
                ],
            ],
        ],

        'attributes' => [
            'lookup' => [
                'click-to-add'    => 'Clique para adicionar',
                'search'          => 'Pesquisar',
                'no-result-found' => 'Nenhum resultado encontrado',
                'search'          => 'Pesquisar...',
            ],
        ],

        'lookup' => [
            'click-to-add' => 'Clique para Adicionar',
            'no-results'   => 'Nenhum Resultado Encontrado',
            'add-as-new'   => 'Adicionar como Novo',
            'search'       => 'Pesquisar...',
        ],

        'flash-group' => [
            'success' => 'Sucesso',
            'error'   => 'Erro',
            'warning' => 'Aviso',
            'info'    => 'Informação',
        ],
    ],

    'quotes' => [
        'index' => [
            'title'          => 'Cotações',
            'create-btn'     => 'Criar Cotação',
            'create-success' => 'Cotação criada com sucesso.',
            'update-success' => 'Cotação atualizada com sucesso.',
            'delete-success' => 'Cotação excluída com sucesso.',
            'delete-failed'  => 'A cotação não pode ser excluída.',

            'datagrid' => [
                'subject'        => 'Assunto',
                'sales-person'   => 'Vendedor',
                'expired-at'     => 'Expirado Em',
                'created-at'     => 'Criado Em',
                'expired-quotes' => 'Cotação Expirada',
                'person'         => 'Pessoa',
                'subtotal'       => 'Subtotal',
                'discount'       => 'Desconto',
                'tax'            => 'Imposto',
                'adjustment'     => 'Ajuste',
                'grand-total'    => 'Total Geral',
                'edit'           => 'Editar',
                'delete'         => 'Excluir',
                'print'          => 'Imprimir',
            ],

            'pdf' => [
                'title'            => 'Cotação',
                'grand-total'      => 'Total Geral',
                'adjustment'       => 'Ajuste',
                'discount'         => 'Desconto',
                'tax'              => 'Imposto',
                'sub-total'        => 'Subtotal',
                'amount'           => 'Valor',
                'quantity'         => 'Quantidade',
                'price'            => 'Preço',
                'product-name'     => 'Nome do Produto',
                'sku'              => 'SKU',
                'shipping-address' => 'Endereço de Entrega',
                'billing-address'  => 'Endereço de Cobrança',
                'expired-at'       => 'Expirado Em',
                'sales-person'     => 'Vendedor',
                'date'             => 'Data',
                'quote-id'         => 'ID da Cotação',
            ],
        ],

        'create' => [
            'title'             => 'Criar Cotação',
            'save-btn'          => 'Salvar Cotação',
            'quote-info'        => 'Informações da Cotação',
            'quote-info-info'   => 'Insira as informações básicas da cotação.',
            'address-info'      => 'Informações de Endereço',
            'address-info-info' => 'Informações sobre o endereço relacionado à cotação.',
            'quote-items'       => 'Itens da Cotação',
            'search-products'   => 'Pesquisar Produtos',
            'link-to-lead'      => 'Vincular ao lead',
            'quote-item-info'   => 'Adicionar Solicitação de Produto para esta cotação.',
            'quote-name'        => 'Nome da cotação',
            'quantity'          => 'Quantidade',
            'price'             => 'Preço',
            'discount'          => 'Desconto',
            'tax'               => 'Imposto',
            'total'             => 'Total',
            'amount'            => 'Valor',
            'add-item'          => '+ Adicionar Item',
            'sub-total'         => 'Subtotal (:symbol)',
            'total-discount'    => 'Desconto (:symbol)',
            'total-tax'         => 'Imposto (:symbol)',
            'total-adjustment'  => 'Ajuste (:symbol)',
            'grand-total'       => 'Total Geral (:symbol)',
            'discount-amount'   => 'Valor do desconto',
            'tax-amount'        => 'Valor do imposto',
            'adjustment-amount' => 'Valor do ajuste',
            'product-name'      => 'Nome do Produto',
            'action'            => 'Ação',
        ],

        'edit' => [
            'title'             => 'Editar Cotação',
            'save-btn'          => 'Salvar Cotação',
            'quote-info'        => 'Informações da Cotação',
            'quote-info-info'   => 'Insira as informações básicas da cotação.',
            'address-info'      => 'Informações de Endereço',
            'address-info-info' => 'Informações sobre o endereço relacionado à cotação.',
            'quote-items'       => 'Itens da Cotação',
            'link-to-lead'      => 'Vincular ao lead',
            'quote-item-info'   => 'Adicionar Solicitação de Produto para esta cotação.',
            'quote-name'        => 'Nome da cotação',
            'quantity'          => 'Quantidade',
            'price'             => 'Preço',
            'search-products'   => 'Pesquisar Produtos',
            'discount'          => 'Desconto',
            'tax'               => 'Imposto',
            'total'             => 'Total',
            'amount'            => 'Valor',
            'add-item'          => '+ Adicionar Item',
            'sub-total'         => 'Subtotal (:symbol)',
            'total-discount'    => 'Desconto (:symbol)',
            'total-tax'         => 'Imposto (:symbol)',
            'total-adjustment'  => 'Ajuste (:symbol)',
            'grand-total'       => 'Total Geral (:symbol)',
            'discount-amount'   => 'Valor do desconto',
            'tax-amount'        => 'Valor do imposto',
            'adjustment-amount' => 'Valor do ajuste',
            'product-name'      => 'Nome do Produto',
            'action'            => 'Ação',
        ],
    ],

    'contacts' => [
        'persons' => [
            'index' => [
                'title'          => 'Pessoas',
                'create-btn'     => 'Criar Pessoa',
                'create-success' => 'Pessoa criada com sucesso.',
                'update-success' => 'Pessoa atualizada com sucesso.',
                'delete-success' => 'Pessoa excluída com sucesso.',
                'delete-failed'  => 'A pessoa não pode ser excluída.',

                'datagrid' => [
                    'contact-numbers'   => 'Números de Contato',
                    'delete'            => 'Excluir',
                    'edit'              => 'Editar',
                    'emails'            => 'E-mails',
                    'id'                => 'ID',
                    'view'              => 'Visualizar',
                    'name'              => 'Nome',
                    'organization-name' => 'Nome da Organização',
                ],
            ],

            'view' => [
                'title'        => ':name',
                'about-person' => 'Sobre a Pessoa',

                'activities' => [
                    'index' => [
                        'all'          => 'Todos',
                        'calls'        => 'Ligações',
                        'meetings'     => 'Reuniões',
                        'lunches'      => 'Almoços',
                        'files'        => 'Arquivos',
                        'quotes'       => 'Cotações',
                        'notes'        => 'Notas',
                        'emails'       => 'E-mails',
                        'by-user'      => 'Por :usuario',
                        'scheduled-on' => 'Agendado para',
                        'location'     => 'Localização',
                        'participants' => 'Participantes',
                        'mark-as-done' => 'Marcar como Concluído',
                        'delete'       => 'Excluir',
                        'edit'         => 'Editar',
                    ],

                    'actions' => [
                        'mail' => [
                            'btn'      => 'E-mail',
                            'title'    => 'Compor E-mail',
                            'to'       => 'Para',
                            'cc'       => 'CC',
                            'bcc'      => 'CCO',
                            'subject'  => 'Assunto',
                            'send-btn' => 'Enviar',
                            'message'  => 'Mensagem',
                        ],

                        'file' => [
                            'btn'           => 'Arquivo',
                            'title'         => 'Adicionar Arquivo',
                            'title-control' => 'Título',
                            'name'          => 'Nome do Arquivo',
                            'description'   => 'Descrição',
                            'file'          => 'Arquivo',
                            'save-btn'      => 'Salvar Arquivo',
                        ],

                        'note' => [
                            'btn'      => 'Nota',
                            'title'    => 'Adicionar Nota',
                            'comment'  => 'Comentário',
                            'save-btn' => 'Salvar Nota',
                        ],

                        'activity' => [
                            'btn'           => 'Atividade',
                            'title'         => 'Adicionar Atividade',
                            'title-control' => 'Título',
                            'description'   => 'Descrição',
                            'schedule-from' => 'Agendar De',
                            'schedule-to'   => 'Agendar Até',
                            'location'      => 'Localização',
                            'call'          => 'Ligação',
                            'meeting'       => 'Reunião',
                            'lunch'         => 'Almoço',
                            'save-btn'      => 'Salvar Atividade',
                        ],
                    ],
                ],
            ],

            'create' => [
                'title'    => 'Criar Pessoa',
                'save-btn' => 'Salvar Pessoa',
            ],

            'edit' => [
                'title'    => 'Editar Pessoa',
                'save-btn' => 'Salvar Pessoa',
            ],
        ],

        'organizations' => [
            'index' => [
                'title'          => 'Organizações',
                'create-btn'     => 'Criar Organização',
                'create-success' => 'Organização criada com sucesso.',
                'update-success' => 'Organização atualizada com sucesso.',
                'delete-success' => 'Organização excluída com sucesso.',
                'delete-failed'  => 'A organização não pode ser excluída.',

                'datagrid' => [
                    'delete'        => 'Excluir',
                    'edit'          => 'Editar',
                    'id'            => 'ID',
                    'name'          => 'Nome',
                    'persons-count' => 'Quantidade de Pessoas',
                ],
            ],

            'create' => [
                'title'    => 'Criar Organização',
                'save-btn' => 'Salvar Organização',
            ],

            'edit' => [
                'title'    => 'Editar Organização',
                'save-btn' => 'Salvar Organização',
            ],
        ],
    ],

    'products' => [
        'index' => [
            'title'          => 'Produtos',
            'create-btn'     => 'Criar Produto',
            'create-success' => 'Produto criado com sucesso.',
            'update-success' => 'Produto atualizado com sucesso.',
            'delete-success' => 'Produto excluído com sucesso.',
            'delete-failed'  => 'O produto não pode ser excluído.',

            'datagrid'   => [
                'allocated' => 'Alocado',
                'delete'    => 'Excluir',
                'edit'      => 'Editar',
                'id'        => 'ID',
                'in-stock'  => 'Em Estoque',
                'name'      => 'Nome',
                'on-hand'   => 'Disponível',
                'price'     => 'Preço',
                'sku'       => 'SKU',
                'view'      => 'Visualizar',
            ],
        ],

        'create' => [
            'save-btn'  => 'Salvar Produtos',
            'title'     => 'Criar Produtos',
            'general'   => 'Geral',
            'price'     => 'Preço',
        ],

        'edit' => [
            'title'     => 'Editar Produtos',
            'save-btn'  => 'Salvar Produtos',
            'general'   => 'Geral',
            'price'     => 'Preço',
        ],

        'view' => [
            'sku'         => 'SKU',
            'all'         => 'Todos',
            'notes'       => 'Notas',
            'files'       => 'Arquivos',
            'inventories' => 'Inventário',
            'change-logs' => 'Registros de Alteração',

            'attributes' => [
                'about-product' => 'Sobre o Produto',
            ],

            'inventory' => [
                'source'     => 'Fonte',
                'in-stock'   => 'Em Estoque',
                'allocated'  => 'Alocado',
                'on-hand'    => 'Disponível',
                'actions'    => 'Ações',
                'assign'     => 'Atribuir',
                'add-source' => 'Adicionar Fonte',
                'location'   => 'Localização',
                'add-more'   => 'Adicionar Mais',
                'save'       => 'Salvar',
            ],
        ],
    ],

    'settings' => [
        'title' => 'Configurações',

        'groups' => [
            'index' => [
                'create-btn'        => 'Criar Grupo',
                'title'             => 'Grupos',
                'create-success'    => 'Grupo criado com sucesso.',
                'update-success'    => 'Grupo atualizado com sucesso.',
                'destroy-success'   => 'Grupo excluído com sucesso.',
                'delete-failed'     => 'O grupo não pode ser excluído.',

                'datagrid'   => [
                    'delete'      => 'Excluir',
                    'description' => 'Descrição',
                    'edit'        => 'Editar',
                    'id'          => 'ID',
                    'name'        => 'Nome',
                ],

                'edit' => [
                    'title' => 'Editar Grupo',
                ],

                'create' => [
                    'name'        => 'Nome',
                    'title'       => 'Criar Grupo',
                    'description' => 'Descrição',
                    'save-btn'    => 'Salvar Grupo',
                ],
            ],
        ],

        'roles' => [
            'index' => [
                'being-used'                => 'A função não pode ser excluída, pois está sendo usada por um usuário administrador.',
                'create-btn'                => 'Criar Funções',
                'create-success'            => 'Função criada com sucesso.',
                'current-role-delete-error' => 'Não é possível excluir a função atribuída ao usuário atual.',
                'delete-failed'             => 'A função não pode ser excluída.',
                'delete-success'            => 'Função excluída com sucesso.',
                'last-delete-error'         => 'É necessária pelo menos uma função.',
                'settings'                  => 'Configurações',
                'title'                     => 'Funções',
                'update-success'            => 'Função atualizada com sucesso.',
                'user-define-error'         => 'Não é possível excluir função do sistema.',

                'datagrid'   => [
                    'all'             => 'Todos',
                    'custom'          => 'Personalizado',
                    'delete'          => 'Excluir',
                    'description'     => 'Descrição',
                    'edit'            => 'Editar',
                    'id'              => 'ID',
                    'name'            => 'Nome',
                    'permission-type' => 'Tipo de Permissão',
                ],
            ],

            'create' => [
                'access-control' => 'Controle de Acesso',
                'all'            => 'Todos',
                'back-btn'       => 'Voltar',
                'custom'         => 'Personalizado',
                'description'    => 'Descrição',
                'general'        => 'Geral',
                'name'           => 'Nome',
                'permissions'    => 'Permissões',
                'save-btn'       => 'Salvar Função',
                'title'          => 'Criar Função',
            ],

            'edit' => [
                'access-control' => 'Controle de Acesso',
                'all'            => 'Todos',
                'back-btn'       => 'Voltar',
                'custom'         => 'Personalizado',
                'description'    => 'Descrição',
                'general'        => 'Geral',
                'name'           => 'Nome',
                'permissions'    => 'Permissões',
                'save-btn'       => 'Salvar Função',
                'title'          => 'Editar Função',
            ],
        ],

        'types' => [
            'index' => [
                'create-btn'     => 'Criar Tipo',
                'create-success' => 'Tipo criado com sucesso.',
                'delete-failed'  => 'O tipo não pode ser excluído.',
                'delete-success' => 'Tipo excluído com sucesso.',
                'title'          => 'Tipos',
                'update-success' => 'Tipo atualizado com sucesso.',

                'datagrid' => [
                    'delete'      => 'Excluir',
                    'description' => 'Descrição',
                    'edit'        => 'Editar',
                    'id'          => 'ID',
                    'name'        => 'Nome',
                ],

                'create' => [
                    'name'     => 'Nome',
                    'save-btn' => 'Salvar Tipo',
                    'title'    => 'Criar Tipo',
                ],

                'edit' => [
                    'title' => 'Editar Tipo',
                ],
            ],
        ],

        'sources' => [
            'index' => [
                'create-btn'     => 'Criar Fonte',
                'create-success' => 'Fonte criada com sucesso.',
                'delete-failed'  => 'A fonte não pode ser excluída.',
                'delete-success' => 'Fonte excluída com sucesso.',
                'title'          => 'Fontes',
                'update-success' => 'Fonte atualizada com sucesso.',

                'datagrid' => [
                    'delete' => 'Excluir',
                    'edit'   => 'Editar',
                    'id'     => 'ID',
                    'name'   => 'Nome',
                ],

                'create' => [
                    'name'     => 'Nome',
                    'save-btn' => 'Salvar Tipo',
                    'title'    => 'Criar Tipo',
                ],

                'edit' => [
                    'title' => 'Editar Tipo',
                ],
            ],
        ],

        'workflows' => [
            'index' => [
                'title'          => 'Fluxos de Trabalho',
                'create-btn'     => 'Criar Fluxo de Trabalho',
                'create-success' => 'Fluxo de trabalho criado com sucesso.',
                'update-success' => 'Fluxo de trabalho atualizado com sucesso.',
                'delete-success' => 'Fluxo de trabalho excluído com sucesso.',
                'delete-failed'  => 'O fluxo de trabalho não pode ser excluído.',
                'datagrid'       => [
                    'delete'      => 'Excluir',
                    'description' => 'Descrição',
                    'edit'        => 'Editar',
                    'id'          => 'ID',
                    'name'        => 'Nome',
                ],
            ],

            'helpers' => [
                'update-related-leads'       => 'Atualizar leads relacionados',
                'send-email-to-sales-owner'  => 'Enviar e-mail para o proprietário de vendas',
                'send-email-to-participants' => 'Enviar e-mail para os participantes',
                'add-webhook'                => 'Adicionar Webhook',
                'update-lead'                => 'Atualizar Lead',
                'update-person'              => 'Atualizar Pessoa',
                'send-email-to-person'       => 'Enviar e-mail para a pessoa',
                'add-tag'                    => 'Adicionar Tag',
                'add-note-as-activity'       => 'Adicionar Nota como Atividade',
            ],

            'create' => [
                'title'                  => 'Criar Fluxo de Trabalho',
                'event'                  => 'Evento',
                'back-btn'               => 'Voltar',
                'save-btn'               => 'Salvar Fluxo de Trabalho',
                'name'                   => 'Nome',
                'basic-details'          => 'Detalhes Básicos',
                'description'            => 'Descrição',
                'actions'                => 'Ações',
                'basic-details-info'     => 'Insira as informações básicas do fluxo de trabalho.',
                'event-info'             => 'Um evento dispara, verifica condições e executa ações predefinidas.',
                'conditions'             => 'Condições',
                'conditions-info'        => 'Condições são regras que verificam cenários, acionadas em ocasiões específicas.',
                'actions-info'           => 'Uma ação não só reduz a carga de trabalho, mas também torna a automação do CRM mais fácil',
                'value'                  => 'Valor',
                'condition-type'         => 'Tipo de Condição',
                'all-condition-are-true' => 'Todas as condições são verdadeiras',
                'any-condition-are-true' => 'Qualquer condição é verdadeira',
                'add-condition'          => 'Adicionar Condição',
                'add-action'             => 'Adicionar Ação',
                'yes'                    => 'Sim',
                'no'                     => 'Não',
                'email'                  => 'E-mail',
                'is-equal-to'            => 'É igual a',
                'is-not-equal-to'        => 'Não é igual a',
                'equals-or-greater-than' => 'Igual ou maior que',
                'equals-or-less-than'    => 'Igual ou menor que',
                'greater-than'           => 'Maior que',
                'less-than'              => 'Menor que',
                'type'                   => 'Tipo',
                'contain'                => 'Contém',
                'contains'               => 'Contém',
                'does-not-contain'       => 'Não contém',
            ],

            'edit' => [
                'title'                  => 'Editar Fluxo de Trabalho',
                'event'                  => 'Evento',
                'back-btn'               => 'Voltar',
                'save-btn'               => 'Salvar Fluxo de Trabalho',
                'name'                   => 'Nome',
                'basic-details'          => 'Detalhes Básicos',
                'description'            => 'Descrição',
                'actions'                => 'Ações',
                'type'                   => 'Tipo',
                'basic-details-info'     => 'Insira as informações básicas do fluxo de trabalho.',
                'event-info'             => 'Um evento dispara, verifica condições e executa ações predefinidas.',
                'conditions'             => 'Condições',
                'conditions-info'        => 'Condições são regras que verificam cenários, acionadas em ocasiões específicas.',
                'actions-info'           => 'Uma ação não só reduz a carga de trabalho, mas também torna a automação do CRM mais fácil',
                'value'                  => 'Valor',
                'condition-type'         => 'Tipo de Condição',
                'all-condition-are-true' => 'Todas as condições são verdadeiras',
                'any-condition-are-true' => 'Qualquer condição é verdadeira',
                'add-condition'          => 'Adicionar Condição',
                'add-action'             => 'Adicionar Ação',
                'yes'                    => 'Sim',
                'no'                     => 'Não',
                'email'                  => 'E-mail',
                'is-equal-to'            => 'É igual a',
                'is-not-equal-to'        => 'Não é igual a',
                'equals-or-greater-than' => 'Igual ou maior que',
                'equals-or-less-than'    => 'Igual ou menor que',
                'greater-than'           => 'Maior que',
                'less-than'              => 'Menor que',
                'contain'                => 'Contém',
                'contains'               => 'Contém',
                'does-not-contain'       => 'Não contém',
            ],
        ],

        'webforms' => [
            'index' => [
                'title'          => 'Formulários Web',
                'create-btn'     => 'Criar Formulário Web',
                'create-success' => 'Formulário web criado com sucesso.',
                'update-success' => 'Formulário web atualizado com sucesso.',
                'delete-success' => 'Formulário web excluído com sucesso.',
                'delete-failed'  => 'O formulário web não pode ser excluído.',

                'datagrid'       => [
                    'id'     => 'ID',
                    'title'  => 'Título',
                    'edit'   => 'Editar',
                    'delete' => 'Excluir',
                ],
            ],

            'create' => [
                'add-attribute-btn'        => 'Adicionar Botão de Atributo',
                'attribute-label-color'    => 'Cor do Rótulo do Atributo',
                'attributes'               => 'Atributos',
                'attributes-info'          => 'Adicione atributos personalizados ao formulário.',
                'background-color'         => 'Cor de Fundo',
                'create-lead'              => 'Criar Lead',
                'customize-webform'        => 'Personalizar Formulário Web',
                'customize-webform-info'   => 'Personalize seu formulário web com cores de elementos de sua escolha.',
                'description'              => 'Descrição',
                'display-custom-message'   => 'Exibir mensagem personalizada',
                'form-background-color'    => 'Cor de Fundo do Formulário',
                'form-submit-btn-color'    => 'Cor do Botão de Envio do Formulário',
                'form-submit-button-color' => 'Cor do Botão de Envio do Formulário',
                'form-title-color'         => 'Cor-Título-Formulário',
                'general'                  => 'Geral',
                'leads'                    => 'Leads',
                'person'                   => 'Pessoa',
                'save-btn'                 => 'Salvar Formulário Web',
                'submit-button-label'      => 'Rótulo do Botão de Envio',
                'submit-success-action'    => 'Ação de Sucesso no Envio',
                'title'                    => 'Criar Formulário Web',
            ],

            'edit' => [
                'add-attribute-btn'         => 'Adicionar Botão de Atributo',
                'attribute-label-color'     => 'Cor do Rótulo do Atributo',
                'attributes'                => 'Atributos',
                'attributes-info'           => 'Adicione atributos personalizados ao formulário.',
                'background-color'          => 'Cor de Fundo',
                'code-snippet'              => 'Trecho de Código',
                'copied'                    => 'Copiado',
                'copy'                      => 'Copiar',
                'create-lead'               => 'Criar Lead',
                'customize-webform'         => 'Personalizar Formulário Web',
                'customize-webform-info'    => 'Personalize seu formulário web com cores de elementos de sua escolha.',
                'description'               => 'Descrição',
                'display-custom-message'    => 'Exibir mensagem personalizada',
                'embed'                     => 'Incorporar',
                'form-background-color'     => 'Cor de Fundo do Formulário',
                'form-submit-btn-color'     => 'Cor do Botão de Envio do Formulário',
                'form-submit-button-color'  => 'Cor do Botão de Envio do Formulário',
                'form-title-color'          => 'Cor do Título do Formulário',
                'general'                   => 'Geral',
                'preview'                   => 'Visualizar',
                'person'                    => 'Pessoa',
                'public-url'                => 'URL Pública',
                'redirect-to-url'           => 'Redirecionar Para URL',
                'save-btn'                  => 'Salvar Formulário Web',
                'submit-button-label'       => 'Rótulo do Botão de Envio',
                'submit-success-action'     => 'Ação de Sucesso no Envio',
                'title'                     => 'Editar Formulário Web',
            ],
        ],

        'email-template' => [
            'index' => [
                'create-btn'     => 'Criar Modelo de E-mail',
                'title'          => 'Modelos de E-mail',
                'create-success' => 'Modelo de e-mail criado com sucesso.',
                'update-success' => 'Modelo de e-mail atualizado com sucesso.',
                'delete-success' => 'Modelo de e-mail excluído com sucesso.',
                'delete-failed'  => 'O modelo de e-mail não pode ser excluído.',

                'datagrid'   => [
                    'delete'       => 'Excluir',
                    'edit'         => 'Editar',
                    'id'           => 'ID',
                    'name'         => 'Nome',
                    'subject'      => 'Assunto',
                ],
            ],

            'create'     => [
                'title'                => 'Criar Modelo de E-mail',
                'save-btn'             => 'Salvar Modelo de E-mail',
                'email-template'       => 'Modelo de E-mail',
                'subject'              => 'Assunto',
                'content'              => 'Conteúdo',
                'subject-placeholders' => 'Marcadores de Assunto',
                'general'              => 'Geral',
                'name'                 => 'Nome',
            ],

            'edit' => [
                'title'                => 'Editar Modelo de E-mail',
                'save-btn'             => 'Salvar Modelo de E-mail',
                'email-template'       => 'Modelo de E-mail',
                'subject'              => 'Assunto',
                'content'              => 'Conteúdo',
                'subject-placeholders' => 'Marcadores de Assunto',
                'general'              => 'Geral',
                'name'                 => 'Nome',
            ],
        ],

        'tags' => [
            'index' => [
                'create-btn'     => 'Criar Tag',
                'title'          => 'Tags',
                'create-success' => 'Tag criada com sucesso.',
                'update-success' => 'Tag atualizada com sucesso.',
                'delete-success' => 'Tag excluída com sucesso.',
                'delete-failed'  => 'A tag não pode ser excluída.',

                'datagrid' => [
                    'delete'      => 'Excluir',
                    'edit'        => 'Editar',
                    'id'          => 'ID',
                    'name'        => 'Nome',
                    'users'       => 'Usuários',
                    'created-at'  => 'Criado Em',
                ],

                'create' => [
                    'name'     => 'Nome',
                    'save-btn' => 'Salvar Tag',
                    'title'    => 'Criar Tag',
                    'color'    => 'Cor',
                ],

                'edit' => [
                    'title' => 'Editar Tag',
                ],
            ],
        ],

        'users' => [
            'index' => [
                'create-btn'          => 'Criar Usuário',
                'create-success'      => 'Usuário criado com sucesso.',
                'delete-failed'       => 'O usuário não pode ser excluído.',
                'delete-success'      => 'Usuário excluído com sucesso.',
                'last-delete-error'   => 'É necessário pelo menos um usuário.',
                'mass-delete-failed'  => 'Os usuários não podem ser excluídos.',
                'mass-delete-success' => 'Usuários excluídos com sucesso.',
                'mass-update-failed'  => 'Os usuários não podem ser atualizados.',
                'mass-update-success' => 'Usuários atualizados com sucesso.',
                'title'               => 'Usuários',
                'update-success'      => 'Usuário atualizado com sucesso.',
                'user-define-error'   => 'Não é possível excluir usuário do sistema.',
                'active'              => 'Ativo',
                'inactive'            => 'Inativo',

                'datagrid' => [
                    'active'        => 'Ativo',
                    'created-at'    => 'Criado Em',
                    'delete'        => 'Excluir',
                    'edit'          => 'Editar',
                    'email'         => 'E-mail',
                    'id'            => 'ID',
                    'inactive'      => 'Inativo',
                    'name'          => 'Nome',
                    'status'        => 'Status',
                    'update-status' => 'Atualizar Status',
                    'users'         => 'Usuários',
                ],

                'create' => [
                    'confirm-password' => 'Confirmar Senha',
                    'email'            => 'E-mail',
                    'general'          => 'Geral',
                    'global'           => 'Global',
                    'group'            => 'Grupo',
                    'individual'       => 'Individual',
                    'name'             => 'Nome',
                    'password'         => 'Senha',
                    'permission'       => 'Permissão',
                    'role'             => 'Função',
                    'save-btn'         => 'Salvar Usuário',
                    'status'           => 'Status',
                    'title'            => 'Criar Usuário',
                    'view-permission'  => 'Ver Permissão',
                ],

                'edit' => [
                    'title' => 'Editar Usuário',
                ],
            ],
        ],

        'pipelines' => [
            'index' => [
                'title'                => 'Funis',
                'create-btn'           => 'Criar Funil',
                'create-success'       => 'Funil criado com sucesso.',
                'update-success'       => 'Funil atualizado com sucesso.',
                'delete-success'       => 'Funil excluído com sucesso.',
                'delete-failed'        => 'O funil não pode ser excluído.',
                'default-delete-error' => 'O funil padrão não pode ser excluído.',

                'datagrid' => [
                    'delete'      => 'Excluir',
                    'edit'        => 'Editar',
                    'id'          => 'ID',
                    'is-default'  => 'É Padrão',
                    'name'        => 'Nome',
                    'no'          => 'Não',
                    'rotten-days' => 'Dias Inativos',
                    'yes'         => 'Sim',
                ],
            ],

            'create' => [
                'title'                => 'Criar Funil',
                'save-btn'             => 'Salvar Funil',
                'name'                 => 'Nome',
                'rotten-days'          => 'Dias Inativos',
                'mark-as-default'      => 'Marcar como Padrão',
                'general'              => 'Geral',
                'probability'          => 'Probabilidade(%)',
                'new-stage'            => 'Novo',
                'won-stage'            => 'Ganho',
                'lost-stage'           => 'Perdido',
                'stage-btn'            => 'Adicionar Etapa',
                'stages'               => 'Etapas',
                'duplicate-name'       => 'O campo "Nome" não pode ser duplicado',
                'delete-stage'         => 'Excluir Etapa',
                'add-new-stages'       => 'Adicionar Novas Etapas',
                'add-stage-info'       => 'Adicione nova etapa para seu Funil',
                'newly-added'          => 'Recém Adicionado',
                'stage-delete-success' => 'Etapa Excluída com Sucesso',
            ],

            'edit'  => [
                'title'                => 'Editar Funil',
                'save-btn'             => 'Salvar Funil',
                'name'                 => 'Nome',
                'rotten-days'          => 'Dias Inativos',
                'mark-as-default'      => 'Marcar como Padrão',
                'general'              => 'Geral',
                'probability'          => 'Probabilidade(%)',
                'new-stage'            => 'Novo',
                'won-stage'            => 'Ganho',
                'lost-stage'           => 'Perdido',
                'stage-btn'            => 'Adicionar Etapa',
                'stages'               => 'Etapas',
                'duplicate-name'       => 'O campo "Nome" não pode ser duplicado',
                'delete-stage'         => 'Excluir Etapa',
                'add-new-stages'       => 'Adicionar Novas Etapas',
                'add-stage-info'       => 'Adicione nova etapa para seu Funil',
                'stage-delete-success' => 'Etapa Excluída com Sucesso',
            ],
        ],

        'webhooks' => [
            'index' => [
                'title'          => 'Webhooks',
                'create-btn'     => 'Criar Webhook',
                'create-success' => 'Webhook criado com sucesso.',
                'update-success' => 'Webhook atualizado com sucesso.',
                'delete-success' => 'Webhook excluído com sucesso.',
                'delete-failed'  => 'O webhook não pode ser excluído.',

                'datagrid' => [
                    'id'          => 'ID',
                    'delete'      => 'Excluir',
                    'edit'        => 'Editar',
                    'name'        => 'Nome',
                    'entity-type' => 'Tipo de Entidade',
                    'end-point'   => 'Ponto Final',
                ],
            ],

            'create' => [
                'title'                 => 'Criar Webhook',
                'save-btn'              => 'Salvar Webhook',
                'info'                  => 'Digite os detalhes dos webhooks',
                'url-and-parameters'    => 'URL e Parâmetros',
                'method'                => 'Método',
                'post'                  => 'Post',
                'put'                   => 'Put',
                'url-endpoint'          => 'URL do Ponto Final',
                'parameters'            => 'Parâmetros',
                'add-new-parameter'     => 'Adicionar Novo Parâmetro',
                'url-preview'           => 'Prévia da URL:',
                'headers'               => 'Cabeçalhos',
                'add-new-header'        => 'Adicionar Novo Cabeçalho',
                'body'                  => 'Corpo',
                'default'               => 'Padrão',
                'x-www-form-urlencoded' => 'x-www-form-urlencoded',
                'raw'                   => 'Raw',
                'general'               => 'Geral',
                'name'                  => 'Nome',
                'entity-type'           => 'Tipo de Entidade',
                'insert-placeholder'    => 'Inserir Marcador',
                'description'           => 'Descrição',
                'json'                  => 'Json',
                'text'                  => 'Texto',
            ],

            'edit' => [
                'title'                 => 'Editar Webhook',
                'edit-btn'              => 'Salvar Webhook',
                'save-btn'              => 'Salvar Webhook',
                'info'                  => 'Insira os detalhes dos webhooks',
                'url-and-parameters'    => 'URL e Parâmetros',
                'method'                => 'Método',
                'post'                  => 'Post',
                'put'                   => 'Put',
                'url-endpoint'          => 'Endpoint da URL',
                'parameters'            => 'Parâmetros',
                'add-new-parameter'     => 'Adicionar Novo Parâmetro',
                'url-preview'           => 'Prévia da URL:',
                'headers'               => 'Cabeçalhos',
                'add-new-header'        => 'Adicionar Novo Cabeçalho',
                'body'                  => 'Corpo',
                'default'               => 'Padrão',
                'x-www-form-urlencoded' => 'x-www-form-urlencoded',
                'raw'                   => 'Raw',
                'general'               => 'Geral',
                'name'                  => 'Nome',
                'entity-type'           => 'Tipo de Entidade',
                'insert-placeholder'    => 'Inserir Placeholder',
                'description'           => 'Descrição',
                'json'                  => 'Json',
                'text'                  => 'Texto',
            ],
        ],

        'warehouses' => [
            'index' => [
                'title'          => 'Depósitos',
                'create-btn'     => 'Criar Depósito',
                'create-success' => 'Depósito criado com sucesso.',
                'name-exists'    => 'Nome do depósito já existe.',
                'update-success' => 'Depósito atualizado com sucesso.',
                'delete-success' => 'Depósito excluído com sucesso.',
                'delete-failed'  => 'O depósito não pode ser excluído.',

                'datagrid' => [
                    'id'              => 'ID',
                    'name'            => 'Nome',
                    'contact-name'    => 'Nome do Contato',
                    'delete'          => 'Excluir',
                    'edit'            => 'Editar',
                    'view'            => 'Visualizar',
                    'created-at'      => 'Criado Em',
                    'products'        => 'Produtos',
                    'contact-emails'  => 'E-mails de Contato',
                    'contact-numbers' => 'Números de Contato',
                ],
            ],

            'create' => [
                'title'         => 'Criar Depósito',
                'save-btn'      => 'Salvar Depósito',
                'contact-info'  => 'Informações de Contato',
            ],

            'edit' => [
                'title'         => 'Editar Depósito',
                'save-btn'      => 'Salvar Depósito',
                'contact-info'  => 'Informações de Contato',
            ],

            'view' => [
                'all'         => 'Todos',
                'notes'       => 'Notas',
                'files'       => 'Arquivos',
                'location'    => 'Localização',
                'change-logs' => 'Logs de Alteração',

                'locations' => [
                    'action'         => 'Ação',
                    'add-location'   => 'Adicionar Localização',
                    'create-success' => 'Localização criada com sucesso.',
                    'delete'         => 'Excluir',
                    'delete-failed'  => 'A localização não pode ser excluída.',
                    'delete-success' => 'Localização excluída com sucesso.',
                    'name'           => 'Nome',
                    'save-btn'       => 'Salvar',
                ],

                'general-information' => [
                    'title' => 'Informações Gerais',
                ],

                'contact-information' => [
                    'title' => 'Informações de Contato',
                ],
            ],
        ],

    'attributes' => [
        'index' => [
            'title'              => 'Atributos',
            'create-btn'         => 'Criar Atributo',
            'create-success'     => 'Atributos criados com sucesso.',
            'update-success'     => 'Atributos atualizados com sucesso.',
            'delete-success'     => 'Atributos excluídos com sucesso.',
            'delete-failed'      => 'Os atributos não podem ser excluídos.',
            'user-define-error'  => 'Não é possível excluir atributo do sistema.',
            'mass-delete-failed' => 'Atributos do sistema não podem ser excluídos.',

            'datagrid' => [
                'yes'         => 'Sim',
                'no'          => 'Não',
                'id'          => 'ID',
                'code'        => 'Código',
                'name'        => 'Nome',
                'entity-type' => 'Tipo de Entidade',
                'type'        => 'Tipo',
                'is-default'  => 'É Padrão',
                'edit'        => 'Editar',
                'delete'      => 'Excluir',
            ],
        ],

        'create'  => [
            'title'                 => 'Criar Atributo',
            'save-btn'              => 'Salvar Atributo',
            'code'                  => 'Código',
            'name'                  => 'Nome',
            'entity-type'           => 'Tipo de Entidade',
            'type'                  => 'Tipo',
            'validations'           => 'Validações',
            'is-required'           => 'É Obrigatório',
            'input-validation'      => 'Validação de Entrada',
            'is-unique'             => 'É Único',
            'labels'                => 'Rótulos',
            'general'               => 'Geral',
            'numeric'               => 'Numérico',
            'decimal'               => 'Decimal',
            'url'                   => 'Url',
            'options'               => 'Opções',
            'option-type'           => 'Tipo de Opção',
            'lookup-type'           => 'Tipo de Consulta',
            'add-option'            => 'Adicionar Opção',
            'save-option'           => 'Salvar Opção',
            'option-name'           => 'Nome da Opção',
            'add-attribute-options' => 'Adicionar Opções de Atributo',
            'text'                  => 'Texto',
            'textarea'              => 'Área de Texto',
            'price'                 => 'Preço',
            'boolean'               => 'Booleano',
            'select'                => 'Seleção',
            'multiselect'           => 'Seleção Múltipla',
            'email'                 => 'E-mail',
            'address'               => 'Endereço',
            'phone'                 => 'Telefone',
            'datetime'              => 'Data e Hora',
            'date'                  => 'Data',
            'image'                 => 'Imagem',
            'file'                  => 'Arquivo',
            'lookup'                => 'Consulta',
            'entity_type'           => 'Tipo de entidade',
            'checkbox'              => 'Caixa de Seleção',
            'is_required'           => 'É Obrigatório',
            'is_unique'             => 'É Único',
        ],

        'edit'  => [
            'title'                 => 'Editar Atributo',
            'save-btn'              => 'Salvar Atributo',
            'code'                  => 'Código',
            'name'                  => 'Nome',
            'labels'                => 'Rótulos',
            'entity-type'           => 'Tipo de Entidade',
            'type'                  => 'Tipo',
            'validations'           => 'Validações',
            'is-required'           => 'É Obrigatório',
            'input-validation'      => 'Validação de Entrada',
            'is-unique'             => 'É Único',
            'general'               => 'Geral',
            'numeric'               => 'Numérico',
            'decimal'               => 'Decimal',
            'url'                   => 'Url',
            'options'               => 'Opções',
            'option-type'           => 'Tipo de Opção',
            'lookup-type'           => 'Tipo de Consulta',
            'add-option'            => 'Adicionar Opção',
            'save-option'           => 'Salvar Opção',
            'option-name'           => 'Nome da Opção',
            'add-attribute-options' => 'Adicionar Opções de Atributo',
            'text'                  => 'Texto',
            'textarea'              => 'Área de Texto',
            'price'                 => 'Preço',
            'boolean'               => 'Booleano',
            'select'                => 'Seleção',
            'multiselect'           => 'Seleção Múltipla',
            'email'                 => 'E-mail',
            'address'               => 'Endereço',
            'phone'                 => 'Telefone',
            'datetime'              => 'Data e Hora',
            'date'                  => 'Data',
            'image'                 => 'Imagem',
            'file'                  => 'Arquivo',
            'lookup'                => 'Consulta',
            'entity_type'           => 'Tipo de entidade',
            'checkbox'              => 'Caixa de Seleção',
            'is_required'           => 'É Obrigatório',
            'is_unique'             => 'É Único',
            ],
        ],
    ],

    'activities' => [
        'index' => [
            'title'      => 'Atividades',

            'datagrid' => [
                'comment'       => 'Comentário',
                'created_at'    => 'Criado Em',
                'created_by'    => 'Criado Por',
                'edit'          => 'Editar',
                'id'            => 'ID',
                'done'          => 'Concluído',
                'not-done'      => 'Não Concluído',
                'lead'          => 'Lead',
                'mass-delete'   => 'Exclusão em Massa',
                'mass-update'   => 'Atualização em Massa',
                'schedule-from' => 'Agendar De',
                'schedule-to'   => 'Agendar Até',
                'schedule_from' => 'Agendar De',
                'schedule_to'   => 'Agendar Até',
                'title'         => 'Título',
                'is_done'       => 'Está Concluído',
                'type'          => 'Tipo',
                'update'        => 'Atualizar',
                'call'          => 'Ligação',
                'meeting'       => 'Reunião',
                'lunch'         => 'Almoço',
            ],
        ],

        'edit' => [
            'title'           => 'Editar Atividade',
            'back-btn'        => 'Voltar',
            'save-btn'        => 'Salvar Atividade',
            'type'            => 'Tipo de Atividade',
            'call'            => 'Ligação',
            'meeting'         => 'Reunião',
            'lunch'           => 'Almoço',
            'schedule_to'     => 'Agendado Até',
            'schedule_from'   => 'Agendado De',
            'location'        => 'Localização',
            'comment'         => 'Comentário',
            'lead'            => 'Lead',
            'participants'    => 'Participantes',
            'general'         => 'Geral',
            'persons'         => 'Pessoas',
            'no-result-found' => 'Registros não encontrados.',
            'users'           => 'Usuários',
        ],

        'updated'              => 'Atualizado :attribute',
        'created'              => 'Criado',
        'duration-overlapping' => 'Os participantes têm outra reunião neste horário. Deseja continuar?',
        'create-success'       => 'Atividade criada com sucesso.',
        'update-success'       => 'Atividade atualizada com sucesso.',
        'overlapping-error'    => 'Os participantes têm outra reunião neste horário.',
        'mass-update-success'  => 'Atividades atualizadas com sucesso.',
        'destroy-success'      => 'Atividade excluída com sucesso.',
        'delete-failed'        => 'A atividade não pode ser excluída.',
    ],

    'mail' => [
        'index' => [
            'compose'           => 'Compor',
            'draft'             => 'Rascunho',
            'inbox'             => 'Caixa de Entrada',
            'outbox'            => 'Caixa de Saída',
            'sent'              => 'Enviados',
            'trash'             => 'Lixeira',
            'compose-mail-btn'  => 'Compor E-mail',
            'btn'               => 'E-mail',
            'mail'              => [
                'title'         => 'Compor E-mail',
                'to'            => 'Para',
                'enter-emails'  => 'Pressione enter para adicionar e-mails',
                'cc'            => 'CC',
                'bcc'           => 'CCO',
                'subject'       => 'Assunto',
                'send-btn'      => 'Enviar',
                'message'       => 'Mensagem',
                'draft'         => 'Rascunho',
            ],

            'datagrid' => [
                'id'            => 'ID',
                'from'          => 'De',
                'to'            => 'Para',
                'subject'       => 'Assunto',
                'tag-name'      => 'Nome da Tag',
                'created-at'    => 'Criado Em',
                'move-to-inbox' => 'Movido para Caixa de Entrada',
                'edit'          => 'Editar',
                'view'          => 'Visualizar',
                'delete'        => 'Excluir',
            ],
        ],

        'create-success'      => 'E-mail enviado com sucesso.',
        'update-success'      => 'E-mail atualizado com sucesso.',
        'mass-update-success' => 'E-mails atualizados com sucesso.',
        'delete-success'      => 'E-mail excluído com sucesso.',
        'delete-failed'       => 'O e-mail não pode ser excluído.',

        'view' => [
            'title'                      => 'E-mails',
            'subject'                    => ':subject',
            'link-mail'                  => 'Vincular E-mail',
            'to'                         => 'Para',
            'cc'                         => 'CC',
            'bcc'                        => 'CCO',
            'reply'                      => 'Responder',
            'reply-all'                  => 'Responder a Todos',
            'forward'                    => 'Encaminhar',
            'delete'                     => 'Excluir',
            'enter-mails'                => 'Digite o endereço de e-mail',
            'rotten-days'                => 'Lead está inativo por :days dias',
            'search-an-existing-lead'    => 'Pesquisar um lead existente',
            'search-an-existing-contact' => 'Pesquisar um contato existente',
            'message'                    => 'Mensagem',
            'add-attachments'            => 'Adicionar Anexos',
            'discard'                    => 'Descartar',
            'send'                       => 'Enviar',
            'no-result-found'            => 'Nenhum resultado encontrado',
            'add-new-contact'            => 'Adicionar Novo Contato',
            'description'                => 'Descrição',
            'search'                     => 'Pesquisar...',
            'add-new-lead'               => 'Adicionar Novo Lead',
            'create-new-contact'         => 'Criar Novo Contato',
            'save-contact'               => 'Salvar Contato',
            'create-lead'                => 'Criar Lead',
            'linked-contact'             => 'Contato Vinculado',
            'link-to-contact'            => 'Vincular ao Contato',
            'link-to-lead'               => 'Vincular ao Lead',
            'linked-lead'                => 'Lead Vinculado',
            'lead-details'               => 'Detalhes do Lead',
            'contact-person'             => 'Pessoa de Contato',
            'product'                    => 'Produto',
            'tags' => [
                'create-success'  => 'Tag criada com sucesso.',
                'destroy-success' => 'Tag deletada com sucesso.',
            ],
        ],
    ],

    'common' => [
        'custom-attributes' => [
            'select-country' => 'Selecionar País',
            'select-state'   => 'Selecionar Estado',
            'state'          => 'Estado',
            'city'           => 'Cidade',
            'postcode'       => 'CEP',
            'work'           => 'Trabalho',
            'home'           => 'Casa',
            'add-more'       => 'Adicionar Mais',
            'select'         => 'Selecionar',
            'country'        => 'País',
            'address'        => 'Endereço',
        ],
    ],

    'leads' => [
        'create-success'    => 'Lead criado com sucesso.',
        'update-success'    => 'Lead atualizado com sucesso.',
        'destroy-success'   => 'Lead excluído com sucesso.',
        'destroy-failed'    => 'O lead não pode ser excluído.',

        'index' => [
            'title'      => 'Leads',
            'create-btn' => 'Criar Lead',

            'datagrid' => [
                'id'                  => 'ID',
                'sales-person'        => 'Vendedor',
                'subject'             => 'Assunto',
                'source'              => 'Fonte',
                'lead-value'          => 'Valor do Lead',
                'lead-type'           => 'Tipo de Lead',
                'tag-name'            => 'Nome da Tag',
                'contact-person'      => 'Pessoa de Contato',
                'stage'               => 'Estágio',
                'rotten-lead'         => 'Lead Inativo',
                'expected-close-date' => 'Data Prevista de Fechamento',
                'created-at'          => 'Criado Em',
                'no'                  => 'Não',
                'yes'                 => 'Sim',
                'delete'              => 'Excluir',
                'mass-delete'         => 'Exclusão em Massa',
                'mass-update'         => 'Atualização em Massa',
            ],

            'kanban' => [
                'rotten-days'            => 'Lead está inativo por :days dias',
                'empty-list'             => 'Sua Lista de Leads está Vazia',
                'empty-list-description' => 'Crie um lead para organizar seus objetivos.',
                'create-lead-btn'        => 'Criar Lead',

                'columns' => [
                    'contact-person'      => 'Pessoa de Contato',
                    'id'                  => 'ID',
                    'lead-type'           => 'Tipo de Lead',
                    'lead-value'          => 'Valor do Lead',
                    'sales-person'        => 'Vendedor',
                    'source'              => 'Fonte',
                    'title'               => 'Título',
                    'tags'                => 'Tags',
                    'expected-close-date' => 'Data Prevista de Fechamento',
                    'created-at'          => 'Criado Em',
                ],

                'toolbar' => [
                    'search' => [
                        'title' => 'Pesquisar',
                    ],

                    'filters' => [
                        'apply-filters' => 'Aplicar Filtros',
                        'clear-all'     => 'Limpar Tudo',
                        'filter'        => 'Filtrar',
                        'filters'       => 'Filtros',
                        'select'        => 'Selecionar',
                    ],
                ],
            ],
        ],

        'create' => [
            'title'          => 'Criar Lead',
            'save-btn'       => 'Salvar',
            'details'        => 'Detalhes',
            'details-info'   => 'Insira as Informações Básicas do Lead',
            'contact-person' => 'Pessoa de Contato',
            'contact-info'   => 'Informações Sobre a Pessoa de Contato',
            'products'       => 'Produtos',
            'products-info'  => 'Informações Sobre os Produtos',
        ],

        'edit' => [
            'title'          => 'Editar Lead',
            'save-btn'       => 'Salvar',
            'details'        => 'Detalhes',
            'details-info'   => 'Insira as Informações Básicas do Lead',
            'contact-person' => 'Pessoa de Contato',
            'contact-info'   => 'Informações Sobre a Pessoa de Contato',
            'products'       => 'Produtos',
            'products-info'  => 'Informações Sobre os Produtos',
        ],

        'common' => [
            'contact' => [
                'name'           => 'Nome',
                'email'          => 'E-mail',
                'contact-number' => 'Número de Contato',
                'organization'   => 'Organização',
            ],

            'products' => [
                'product-name' => 'Nome do Produto',
                'quantity'     => 'Quantidade',
                'price'        => 'Preço',
                'amount'       => 'Valor',
                'action'       => 'Ação',
                'add-more'     => 'Adicionar Mais',
                'total'        => 'Total',
            ],
        ],

        'view' => [
            'title'       => 'Lead: :title',
            'rotten-days' => ':days Dias',

            'tabs'        => [
                'description' => 'Descrição',
                'products'    => 'Produtos',
                'quotes'      => 'Cotações',
            ],

            'attributes' => [
                'title' => 'Sobre o Lead',
            ],

            'quotes'=> [
                'subject'         => 'Assunto',
                'expired-at'      => 'Expirado Em',
                'sub-total'       => 'Subtotal',
                'discount'        => 'Desconto',
                'tax'             => 'Imposto',
                'adjustment'      => 'Ajuste',
                'grand-total'     => 'Total Geral',
                'delete'          => 'Excluir',
                'edit'            => 'Editar',
                'download'        => 'Baixar',
                'destroy-success' => 'Cotação excluída com sucesso.',
                'empty-title'     => 'Nenhuma Cotação Encontrada',
                'empty-info'      => 'Nenhuma Cotação Encontrada para este Lead',
                'add-btn'         => 'Adicionar Cotação',
            ],

            'products' => [
                'product-name' => 'Nome do Produto',
                'quantity'     => 'Quantidade',
                'price'        => 'Preço',
                'amount'       => 'Valor',
                'action'       => 'Ação',
                'add-more'     => 'Adicionar Mais',
                'total'        => 'Total',
                'empty-title'  => 'Nenhum Produto Encontrado',
                'empty-info'   => 'Nenhum Produto Encontrado para este Lead',
                'add-product'  => 'Adicionar Produto',
            ],

            'persons' => [
                'title'     => 'Sobre as Pessoas',
                'job-title' => ':job_title em :organization',
            ],

            'stages' => [
                'won-lost'       => 'Ganho/Perdido',
                'won'            => 'Ganho',
                'lost'           => 'Perdido',
                'need-more-info' => 'Necessita Mais Detalhes',
                'closed-at'      => 'Fechado Em',
                'won-value'      => 'Valor Ganho',
                'lost-reason'    => 'Motivo da Perda',
                'save-btn'       => 'Salvar',
            ],

            'tags' => [
                'create-success'  => 'Tag criada com sucesso.',
                'destroy-success' => 'Tag excluída com sucesso.',
            ],
        ],
    ],

    'configuration' => [
    'index' => [
        'back'         => 'Voltar',
        'save-btn'     => 'Salvar Configuração',
        'save-success' => 'Configuração Salva com Sucesso.',
        'search'       => 'Pesquisar',
        'title'        => 'Configuração',

        'general'  => [
            'title'   => 'Geral',
            'info'    => 'Configuração Geral',

            'general' => [
                'title'           => 'Geral',
                'info'            => 'Atualize suas configurações gerais aqui.',
                'locale-settings' => [
                    'title'       => 'Configurações de Localização',
                    'title-info'  => 'Define o idioma usado na interface do usuário, como Português (pt), Inglês (en), Francês (fr) ou Japonês (ja).',
                ],
            ],
        ],
    ],
],

    'dashboard' => [
    'index' => [
        'title' => 'Painel',

        'revenue' => [
            'lost-revenue' => 'Receita Perdida',
            'won-revenue'  => 'Receita Ganha',
        ],

        'over-all' => [
            'average-lead-value'    => 'Valor Médio do Lead',
            'total-leads'           => 'Total de Leads',
            'average-leads-per-day' => 'Média de Leads por Dia',
            'total-quotations'      => 'Total de Cotações',
            'total-persons'         => 'Total de Pessoas',
            'total-organizations'   => 'Total de Organizações',
        ],

        'total-leads' => [
            'title' => 'Leads',
            'total' => 'Total de Leads',
            'won'   => 'Leads Ganhos',
            'lost'  => 'Leads Perdidos',
        ],

        'revenue-by-sources' => [
            'title'       => 'Receita por Fontes',
            'empty-title' => 'Nenhum Dado Disponível',
            'empty-info'  => 'Nenhum dado disponível para o intervalo selecionado',
        ],

        'revenue-by-types' => [
            'title'       => 'Receita por Tipos',
            'empty-title' => 'Nenhum Dado Disponível',
            'empty-info'  => 'Nenhum dado disponível para o intervalo selecionado',
        ],

        'top-selling-products' => [
            'title'       => 'Principais Produtos',
            'empty-title' => 'Nenhum Produto Encontrado',
            'empty-info'  => 'Nenhum produto disponível para o intervalo selecionado',
        ],

        'top-persons' => [
            'title'       => 'Principais Pessoas',
            'empty-title' => 'Nenhuma Pessoa Encontrada',
            'empty-info'  => 'Nenhuma pessoa disponível para o intervalo selecionado',
        ],

        'open-leads-by-states' => [
            'title'       => 'Leads Abertos por Estados',
            'empty-title' => 'Nenhum Dado Disponível',
            'empty-info'  => 'Nenhum dado disponível para o intervalo selecionado',
            ],
        ],
    ],

    'layouts' => [
    'app-version'          => 'Versão: :version',
    'dashboard'            => 'Painel',
    'leads'               => 'Leads',
    'quotes'              => 'Cotações',
    'quote'               => 'Cotação',
    'mail'                => [
        'title'   => 'E-mail',
        'compose' => 'Compor',
        'inbox'   => 'Caixa de Entrada',
        'draft'   => 'Rascunho',
        'outbox'  => 'Caixa de Saída',
        'sent'    => 'Enviados',
        'trash'   => 'Lixeira',
        'setting' => 'Configuração',
    ],
    'activities'           => 'Atividades',
    'contacts'             => 'Contatos',
    'persons'              => 'Pessoas',
    'person'               => 'Pessoa',
    'organizations'        => 'Organizações',
    'organization'         => 'Organização',
    'products'             => 'Produtos',
    'product'              => 'Produto',
    'settings'             => 'Configurações',
    'user'                 => 'Usuário',
    'user-info'            => 'Gerencie todos os seus usuários e suas permissões no CRM, o que eles podem fazer.',
    'groups'               => 'Grupos',
    'groups-info'          => 'Adicione, edite ou exclua grupos do CRM',
    'roles'                => 'Funções',
    'role'                 => 'Função',
    'roles-info'           => 'Adicione, edite ou exclua funções do CRM',
    'users'                => 'Usuários',
    'users-info'           => 'Adicione, edite ou exclua usuários do CRM',
    'lead'                 => 'Lead',
    'lead-info'            => 'Gerencie todas as configurações relacionadas aos leads no CRM',
    'pipelines'            => 'Pipelines',
    'pipelines-info'       => 'Adicione, edite ou exclua pipelines do CRM',
    'sources'              => 'Fontes',
    'sources-info'         => 'Adicione, edite ou exclua fontes do CRM',
    'types'                => 'Tipos',
    'types-info'           => 'Adicione, edite ou exclua tipos do CRM',
    'automation'           => 'Automação',
    'automation-info'      => 'Gerencie todas as configurações relacionadas à automação no CRM',
    'attributes'           => 'Atributos',
    'attribute'            => 'Atributo',
    'attributes-info'      => 'Adicione, edite ou exclua atributos do CRM',
    'email-templates'      => 'Modelos de E-mail',
    'email'                => 'E-mail',
    'email-templates-info' => 'Adicione, edite ou exclua modelos de e-mail do CRM',
    'workflows'            => 'Fluxos de Trabalho',
    'workflows-info'       => 'Adicione, edite ou exclua fluxos de trabalho do CRM',
    'other-settings'       => 'Outras Configurações',
    'other-settings-info'  => 'Gerencie todas as suas configurações extras no CRM',
    'tags'                 => 'Tags',
    'tags-info'            => 'Adicione, edite ou exclua tags do CRM',
    'my-account'           => 'Minha Conta',
    'sign-out'             => 'Sair',
    'back'                 => 'Voltar',
    'name'                 => 'Nome',
    'configuration'        => 'Configuração',
    'activities'           => 'Atividades',
    'howdy'                => 'Olá!',
    'warehouses'           => 'Depósitos',
    'warehouse'            => 'Depósito',
    'warehouses-info'      => 'Adicione, edite ou exclua depósitos do CRM',
    ],

    'user' => [
        'account' => [
            'name'                  => 'Nome',
            'email'                 => 'Email',
            'password'              => 'Senha',
            'my_account'            => 'Minha Conta',
            'update_details'        => 'Atualizar Detalhes',
            'current_password'      => 'Senha Atual',
            'confirm_password'      => 'Confirmar Senha',
            'password-match'        => 'A senha atual não corresponde.',
            'account-save'          => 'Alterações da conta salvas com sucesso.',
            'permission-denied'     => 'Permissão Negada',
            'remove-image'          => 'Remover Imagem',
            'upload_image_pix'      => 'Carregar imagem de Perfil (100px x 100px)',
            'upload_image_format'   => 'em Formato PNG ou JPG',
            'image_upload_message'  => 'Apenas imagens (.jpeg, .jpg, .png, ..) são permitidas.',
        ],
    ],

    'emails' => [
        'common' => [
            'dear'   => 'Prezado :nome',
            'cheers' => 'Atenciosamente,</br>Equipe :app_name',
        ],
    ],

    'errors' => [
        '401' => 'Você não está autorizado a acessar esta página',
    ],
];
