#!/bin/bash

#########################################################
#
# DEFININDO VARIAVIES
#

amarelo="\e[33m"
branco="\e[97m"
bege="\e[93m"
vermelho="\e[91m"
reset="\e[0m"

arquivo="/root/dados_vps/dados_vps"

#
#
#
#########################################################
#
# FUNÇÕES DE NOMES, DIREITOS E OUTROS.
#

nome_instalador() {
    clear
    echo ""
    echo -e "$branco       ███████╗███████╗████████╗██╗   ██╗██████╗      ██████╗ ██████╗ ██╗ ██████╗ ███╗   ██╗\e[0m"
    echo -e "$branco       ██╔════╝██╔════╝╚══██╔══╝██║   ██║██╔══██╗    ██╔═══██╗██╔══██╗██║██╔═══██╗████╗  ██║\e[0m"
    echo -e "$branco       ███████╗█████╗     ██║   ██║   ██║██████╔╝    ██║   ██║██████╔╝██║██║   ██║██╔██╗ ██║\e[0m"
    echo -e "$branco       ╚════██║██╔══╝     ██║   ██║   ██║██╔═══╝     ██║   ██║██╔══██╗██║██║   ██║██║╚██╗██║\e[0m"
    echo -e "$branco       ███████║███████╗   ██║   ╚██████╔╝██║         ╚██████╔╝██║  ██║██║╚██████╔╝██║ ╚████║\e[0m"
    echo -e "$branco       ╚══════╝╚══════╝   ╚═╝    ╚═════╝ ╚═╝          ╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝\e[0m"
    echo -e "$branco                                                                                            \e[0m"
    echo -e "$branco                                        ██╗   ██╗  ██████╗                                  \e[0m"
    echo -e "$branco                                        ██║   ██║  ╚════██╗                                 \e[0m"
    echo -e "$branco                              █████╗    ██║   ██║   █████╔╝    █████╗                       \e[0m"
    echo -e "$branco                              ╚════╝    ╚██╗ ██╔╝  ██╔═══╝     ╚════╝                       \e[0m"
    echo -e "$branco                                         ╚████╔╝██╗███████╗                                 \e[0m"
    echo -e "$branco                                          ╚═══╝ ╚═╝╚══════╝                                 \e[0m"
    echo ""
    echo ""

}
nome_menu() {
    clear
    echo ""
    echo -e "$branco                    ███╗   ███╗███████╗███╗   ██╗██╗   ██╗    ██████╗ ███████╗                \e[0m"
    echo -e "$branco                    ████╗ ████║██╔════╝████╗  ██║██║   ██║    ██╔══██╗██╔════╝                \e[0m"
    echo -e "$branco                    ██╔████╔██║█████╗  ██╔██╗ ██║██║   ██║    ██║  ██║█████╗                  \e[0m"
    echo -e "$branco                    ██║╚██╔╝██║██╔══╝  ██║╚██╗██║██║   ██║    ██║  ██║██╔══╝                  \e[0m"
    echo -e "$branco                    ██║ ╚═╝ ██║███████╗██║ ╚████║╚██████╔╝    ██████╔╝███████╗                \e[0m"
    echo -e "$branco                    ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝ ╚═════╝     ╚═════╝ ╚══════╝                \e[0m"
    echo -e "$branco                                                                                                \e[0m"
    echo -e "$branco  ███████╗███████╗██████╗ ██████╗  █████╗ ███╗   ███╗███████╗███╗   ██╗████████╗ █████╗ ███████╗\e[0m"
    echo -e "$branco  ██╔════╝██╔════╝██╔══██╗██╔══██╗██╔══██╗████╗ ████║██╔════╝████╗  ██║╚══██╔══╝██╔══██╗██╔════╝\e[0m"
    echo -e "$branco  █████╗  █████╗  ██████╔╝██████╔╝███████║██╔████╔██║█████╗  ██╔██╗ ██║   ██║   ███████║███████╗\e[0m"
    echo -e "$branco  ██╔══╝  ██╔══╝  ██╔══██╗██╔══██╗██╔══██║██║╚██╔╝██║██╔══╝  ██║╚██╗██║   ██║   ██╔══██║╚════██║\e[0m"
    echo -e "$branco  ██║     ███████╗██║  ██║██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║ ╚████║   ██║   ██║  ██║███████║\e[0m"
    echo -e "$branco  ╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝╚══════╝\e[0m"
    echo ""
    echo ""



}

direitos_instalador() {
    echo -e "$amarelo===================================================================================================\e[0m"
    echo -e "$amarelo=                                                                                                 =\e[0m"
    echo -e "$amarelo=  $branco Este auto instalador foi desenvolvido para auxiliar na instalação das principais aplicações $amarelo  =\e[0m"
    echo -e "$amarelo=  $branco  disponiveis no mercado open source. Já deixo todos os créditos as desenvolvedores de cada  $amarelo  =\e[0m"
    echo -e "$amarelo=  $branco aplicação disponiveis aqui. Este Setup é licenciado sob a Licença MIT (MIT). Você pode usar,$amarelo  =\e[0m"
    echo -e "$amarelo=  $branco  copiar, modificar, integrar, publicar, distribuir e/ou vender cópias dos produtos finais,  $amarelo  =\e[0m"
    echo -e "$amarelo=  $branco   mas deve sempre declarar que OrionDesign (contato@oriondesign.art.br) é o autor original  $amarelo  =\e[0m"
    echo -e "$amarelo=  $branco           destes códigos e atribuir um link para https://setup.oriondesign.art.br           $amarelo  =\e[0m"
    echo -e "$amarelo=                                                                                                 =\e[0m"
    echo -e "$amarelo===================================================================================================\e[0m"
    echo ""
    echo ""
    read -p "Ao digitar Y você aceita e concorda com as orientações passadas acima (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        clear
        echo "Que pena que você não concorda, então estarei encerrando o instalador. Até mais."
        sleep 2
        clear
        exit 1
    fi
}

preencha_as_info() {
    echo -e "$amarelo===================================================================================================\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo=                          $branco Preencha as informações solicitadas abaixo                            $amarelo=\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo===================================================================================================\e[0m"
    echo ""
    echo ""
}

conferindo_as_info() {
    echo -e "$amarelo===================================================================================================\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo=                          $branco Verifique se os dados abaixos estão certos                            $amarelo=\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo===================================================================================================\e[0m"
    echo ""
    echo ""
}

instalando_msg() {
  echo""
  echo -e "$amarelo===================================================================================================\e[0m"
  echo -e "$amarelo=                                                                                                 =\e[0m"
  echo -e "$amarelo=      $branco  ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗      █████╗ ███╗   ██╗██████╗  ██████╗   $amarelo      = \e[0m" 
  echo -e "$amarelo=      $branco  ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗██╔═══██╗  $amarelo      =\e[0m"
  echo -e "$amarelo=      $branco  ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ███████║██╔██╗ ██║██║  ██║██║   ██║  $amarelo      =\e[0m"
  echo -e "$amarelo=      $branco  ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██╔══██║██║╚██╗██║██║  ██║██║   ██║  $amarelo      =\e[0m"
  echo -e "$amarelo=      $branco  ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝╚██████╔╝  $amarelo      =\e[0m"
  echo -e "$amarelo=      $branco  ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝   $amarelo      =\e[0m"
  echo -e "$amarelo=                                                                                                 =\e[0m"
  echo -e "$amarelo===================================================================================================\e[0m"
  echo ""
  echo ""
}

instalado_msg() {
    clear
    echo ""
    echo -e "$branco     ██╗      ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗      █████╗ ██████╗  ██████╗       ██╗\e[0m"
    echo -e "$branco     ╚██╗     ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██╔══██╗██╔══██╗██╔═══██╗     ██╔╝\e[0m"
    echo -e "$branco      ╚██╗    ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ███████║██║  ██║██║   ██║    ██╔╝ \e[0m"
    echo -e "$branco      ██╔╝    ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██╔══██║██║  ██║██║   ██║    ╚██╗ \e[0m"
    echo -e "$branco     ██╔╝     ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗██║  ██║██████╔╝╚██████╔╝     ╚██╗\e[0m"
    echo -e "$branco     ╚═╝      ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝  ╚═════╝       ╚═╝\e[0m"
    echo ""
    echo ""
}

creditos_msg() {
    echo ""
    echo ""
    echo -e "$amarelo===================================================================================================\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo=          $branco  Gostaria de contribuir para continuarmos o desenvolvimento deste projeto?            $amarelo=\e[0m"
    echo -e "$amarelo=          $branco                    Você pode fazer uma doação via PIX:                                $amarelo=\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo=                                      pix@oriondesign.art.br                                     $amarelo=\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo=          $branco         Se precisar de ajuda/mentoria ou quiser deixar seu feedback                   $amarelo=\e[0m"
    echo -e "$amarelo=          $branco             https://github.com/oriondesign2015/SetupOrion/issues                      $amarelo=\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo=          $branco                               ou via WhatsApp                                         $amarelo=\e[0m"
    echo -e "$amarelo=          $branco              https://api.whatsapp.com/send?phone=5511973052593                        $amarelo=\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo===================================================================================================\e[0m"
    echo ""
    echo ""
}

guarde_os_dados_msg() {
    echo -e "$amarelo===================================================================================================\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo=                 $branco Guarde todos os dados abaixo para evitar futuros transtornos                   $amarelo=\e[0m"
    echo -e "$amarelo=                                                                                                 $amarelo=\e[0m"
    echo -e "$amarelo===================================================================================================\e[0m"
    echo ""
    echo ""
}
dados() {
    nome_servidor=$(grep "Nome do Servidor:" "$arquivo" | awk -F': ' '{print $2}')
    nome_rede_interna=$(grep "Rede interna:" "$arquivo" | awk -F': ' '{print $2}')
}
gerador_de_senha_traefik() {
  senha=$(docker run --rm httpd:2.4-alpine htpasswd -nbB admin '@OrionDesign_' | cut -d ":" -f 2 | sed 's/\$/\$\$/g') > /dev/null 2>&1
}

nome_traefik_e_portainer() {
    clear
    echo ""
    echo -e "$branco               ████████╗██████╗  █████╗ ███████╗███████╗██╗██╗  ██╗    ███████╗       \e[0m"
    echo -e "$branco               ╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██╔════╝██║██║ ██╔╝    ██╔════╝       \e[0m"
    echo -e "$branco                  ██║   ██████╔╝███████║█████╗  █████╗  ██║█████╔╝     █████╗         \e[0m"
    echo -e "$branco                  ██║   ██╔══██╗██╔══██║██╔══╝  ██╔══╝  ██║██╔═██╗     ██╔══╝         \e[0m"
    echo -e "$branco                  ██║   ██║  ██║██║  ██║███████╗██║     ██║██║  ██╗    ███████╗       \e[0m"
    echo -e "$branco                  ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝    ╚══════╝       \e[0m"
    echo -e "$branco                                                                                      \e[0m"
    echo -e "$branco             ██████╗  ██████╗ ██████╗ ████████╗ █████╗ ██╗███╗   ██╗███████╗██████╗   \e[0m"
    echo -e "$branco             ██╔══██╗██╔═══██╗██╔══██╗╚══██╔══╝██╔══██╗██║████╗  ██║██╔════╝██╔══██╗  \e[0m"
    echo -e "$branco             ██████╔╝██║   ██║██████╔╝   ██║   ███████║██║██╔██╗ ██║█████╗  ██████╔╝  \e[0m"
    echo -e "$branco             ██╔═══╝ ██║   ██║██╔══██╗   ██║   ██╔══██║██║██║╚██╗██║██╔══╝  ██╔══██╗  \e[0m"
    echo -e "$branco             ██║     ╚██████╔╝██║  ██║   ██║   ██║  ██║██║██║ ╚████║███████╗██║  ██║  \e[0m"
    echo -e "$branco             ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝  \e[0m"
    echo ""
    echo ""
}

nome_chatwoot(){
    clear
    echo ""
    echo -e "$branco         ██████╗██╗  ██╗ █████╗ ████████╗██╗    ██╗ ██████╗  ██████╗ ████████╗\e[0m"
    echo -e "$branco        ██╔════╝██║  ██║██╔══██╗╚══██╔══╝██║    ██║██╔═══██╗██╔═══██╗╚══██╔══╝\e[0m"
    echo -e "$branco        ██║     ███████║███████║   ██║   ██║ █╗ ██║██║   ██║██║   ██║   ██║   \e[0m"
    echo -e "$branco        ██║     ██╔══██║██╔══██║   ██║   ██║███╗██║██║   ██║██║   ██║   ██║   \e[0m"
    echo -e "$branco        ╚██████╗██║  ██║██║  ██║   ██║   ╚███╔███╔╝╚██████╔╝╚██████╔╝   ██║   \e[0m"
    echo -e "$branco         ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝    ╚══╝╚══╝  ╚═════╝  ╚═════╝    ╚═╝   \e[0m"
    echo ""
    echo ""
}

nome_evolution() {
    clear
    echo ""
    echo -e "$branco ███████╗██╗   ██╗ ██████╗ ██╗     ██╗   ██╗████████╗██╗ ██████╗ ███╗   ██╗     █████╗ ██████╗ ██╗\e[0m"
    echo -e "$branco ██╔════╝██║   ██║██╔═══██╗██║     ██║   ██║╚══██╔══╝██║██╔═══██╗████╗  ██║    ██╔══██╗██╔══██╗██║\e[0m"
    echo -e "$branco █████╗  ██║   ██║██║   ██║██║     ██║   ██║   ██║   ██║██║   ██║██╔██╗ ██║    ███████║██████╔╝██║\e[0m"
    echo -e "$branco ██╔══╝  ╚██╗ ██╔╝██║   ██║██║     ██║   ██║   ██║   ██║██║   ██║██║╚██╗██║    ██╔══██║██╔═══╝ ██║\e[0m"
    echo -e "$branco ███████╗ ╚████╔╝ ╚██████╔╝███████╗╚██████╔╝   ██║   ██║╚██████╔╝██║ ╚████║    ██║  ██║██║     ██║\e[0m"
    echo -e "$branco ╚══════╝  ╚═══╝   ╚═════╝ ╚══════╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝    ╚═╝  ╚═╝╚═╝     ╚═╝\e[0m"
    echo ""
    echo ""                                                                                        
}

nome_typebot() {
    clear
    echo ""
    echo -e "$branco                    ████████╗██╗   ██╗██████╗ ███████╗██████╗  ██████╗ ████████╗\e[0m"
    echo -e "$branco                    ╚══██╔══╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝\e[0m"
    echo -e "$branco                       ██║    ╚████╔╝ ██████╔╝█████╗  ██████╔╝██║   ██║   ██║   \e[0m"
    echo -e "$branco                       ██║     ╚██╔╝  ██╔═══╝ ██╔══╝  ██╔══██╗██║   ██║   ██║   \e[0m"
    echo -e "$branco                       ██║      ██║   ██║     ███████╗██████╔╝╚██████╔╝   ██║   \e[0m"
    echo -e "$branco                       ╚═╝      ╚═╝   ╚═╝     ╚══════╝╚═════╝  ╚═════╝    ╚═╝   \e[0m"
    echo ""
    echo ""                                                    
}

nome_minio() {
    clear
    echo ""
    echo -e "$branco                              ███╗   ███╗██╗███╗   ██╗██╗ ██████╗ \e[0m"
    echo -e "$branco                              ████╗ ████║██║████╗  ██║██║██╔═══██╗\e[0m"
    echo -e "$branco                              ██╔████╔██║██║██╔██╗ ██║██║██║   ██║\e[0m"
    echo -e "$branco                              ██║╚██╔╝██║██║██║╚██╗██║██║██║   ██║\e[0m"
    echo -e "$branco                              ██║ ╚═╝ ██║██║██║ ╚████║██║╚██████╔╝\e[0m"
    echo -e "$branco                              ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝ ╚═════╝ \e[0m"
    echo ""
    echo ""                                   
}

nome_n8n() {
    clear
    echo ""
    echo -e "$branco                            ███╗   ██╗ █████╗ ███╗   ██╗\e[0m"
    echo -e "$branco                            ████╗  ██║██╔══██╗████╗  ██║\e[0m"
    echo -e "$branco                            ██╔██╗ ██║╚█████╔╝██╔██╗ ██║\e[0m"
    echo -e "$branco                            ██║╚██╗██║██╔══██╗██║╚██╗██║\e[0m"
    echo -e "$branco                            ██║ ╚████║╚█████╔╝██║ ╚████║\e[0m"
    echo -e "$branco                            ╚═╝  ╚═══╝ ╚════╝ ╚═╝  ╚═══╝\e[0m"
    echo ""
    echo ""                     
}
nome_flowise() {
    clear
    echo ""
    echo -e "$branco                      ███████╗██╗      ██████╗ ██╗    ██╗██╗███████╗███████╗\e[0m"
    echo -e "$branco                      ██╔════╝██║     ██╔═══██╗██║    ██║██║██╔════╝██╔════╝\e[0m"
    echo -e "$branco                      █████╗  ██║     ██║   ██║██║ █╗ ██║██║███████╗█████╗  \e[0m"
    echo -e "$branco                      ██╔══╝  ██║     ██║   ██║██║███╗██║██║╚════██║██╔══╝  \e[0m"
    echo -e "$branco                      ██║     ███████╗╚██████╔╝╚███╔███╔╝██║███████║███████╗\e[0m"
    echo -e "$branco                      ╚═╝     ╚══════╝ ╚═════╝  ╚══╝╚══╝ ╚═╝╚══════╝╚══════╝\e[0m"
    echo ""
    echo ""
}

nome_pgAdmin_4() {
    clear
    echo ""
    echo -e "$branco               ██████╗  ██████╗  █████╗ ██████╗ ███╗   ███╗██╗███╗   ██╗    ██╗  ██╗\e[0m"
    echo -e "$branco               ██╔══██╗██╔════╝ ██╔══██╗██╔══██╗████╗ ████║██║████╗  ██║    ██║  ██║\e[0m"
    echo -e "$branco               ██████╔╝██║  ███╗███████║██║  ██║██╔████╔██║██║██╔██╗ ██║    ███████║\e[0m"
    echo -e "$branco               ██╔═══╝ ██║   ██║██╔══██║██║  ██║██║╚██╔╝██║██║██║╚██╗██║    ╚════██║\e[0m"
    echo -e "$branco               ██║     ╚██████╔╝██║  ██║██████╔╝██║ ╚═╝ ██║██║██║ ╚████║         ██║\e[0m"
    echo -e "$branco               ╚═╝      ╚═════╝ ╚═╝  ╚═╝╚═════╝ ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝         ╚═╝\e[0m"
    echo ""
    echo ""                                                                  
}

nome_nocobase() {
    clear
    echo ""
    echo -e "$branco               ███╗   ██╗ ██████╗  ██████╗ ██████╗ ██████╗  █████╗ ███████╗███████╗\e[0m"
    echo -e "$branco               ████╗  ██║██╔═══██╗██╔════╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝██╔════╝\e[0m"
    echo -e "$branco               ██╔██╗ ██║██║   ██║██║     ██║   ██║██████╔╝███████║███████╗█████╗  \e[0m"
    echo -e "$branco               ██║╚██╗██║██║   ██║██║     ██║   ██║██╔══██╗██╔══██║╚════██║██╔══╝  \e[0m"
    echo -e "$branco               ██║ ╚████║╚██████╔╝╚██████╗╚██████╔╝██████╔╝██║  ██║███████║███████╗\e[0m"
    echo -e "$branco               ╚═╝  ╚═══╝ ╚═════╝  ╚═════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝\e[0m"
    echo ""
    echo ""                                                                 
}

nome_botpress() {
    clear
    echo ""
    echo -e "$branco              ██████╗  ██████╗ ████████╗██████╗ ██████╗ ███████╗███████╗███████╗\e[0m"
    echo -e "$branco              ██╔══██╗██╔═══██╗╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝\e[0m"
    echo -e "$branco              ██████╔╝██║   ██║   ██║   ██████╔╝██████╔╝█████╗  ███████╗███████╗\e[0m"
    echo -e "$branco              ██╔══██╗██║   ██║   ██║   ██╔═══╝ ██╔══██╗██╔══╝  ╚════██║╚════██║\e[0m"
    echo -e "$branco              ██████╔╝╚██████╔╝   ██║   ██║     ██║  ██║███████╗███████║███████║\e[0m"
    echo -e "$branco              ╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝\e[0m"
    echo ""
    echo ""                                                          
}

nome_remover_stack() {
    clear
    echo ""
    echo -e "$branco                  ██████╗ ███████╗███╗   ███╗ ██████╗ ██╗   ██╗███████╗██████╗ \e[0m"
    echo -e "$branco                  ██╔══██╗██╔════╝████╗ ████║██╔═══██╗██║   ██║██╔════╝██╔══██╗\e[0m"
    echo -e "$branco                  ██████╔╝█████╗  ██╔████╔██║██║   ██║██║   ██║█████╗  ██████╔╝\e[0m"
    echo -e "$branco                  ██╔══██╗██╔══╝  ██║╚██╔╝██║██║   ██║╚██╗ ██╔╝██╔══╝  ██╔══██╗\e[0m"
    echo -e "$branco                  ██║  ██║███████╗██║ ╚═╝ ██║╚██████╔╝ ╚████╔╝ ███████╗██║  ██║\e[0m"
    echo -e "$branco                  ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝ ╚═════╝   ╚═══╝  ╚══════╝╚═╝  ╚═╝\e[0m"
    echo -e "$branco                                                                               \e[0m"
    echo -e "$branco                           ███████╗████████╗ █████╗  ██████╗██╗  ██╗            \e[0m"
    echo -e "$branco                           ██╔════╝╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝            \e[0m"
    echo -e "$branco                           ███████╗   ██║   ███████║██║     █████╔╝             \e[0m"
    echo -e "$branco                           ╚════██║   ██║   ██╔══██║██║     ██╔═██╗             \e[0m"
    echo -e "$branco                           ███████║   ██║   ██║  ██║╚██████╗██║  ██╗            \e[0m"
    echo -e "$branco                           ╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝            \e[0m"
    echo ""
    echo ""                                                                                             
}

verificar_container_postgres() {
    if docker ps -q --filter "name=postgres" | grep -q .; then
        return 0
    else
        return 1
    fi
}

pegar_senha_postgres() {
    senha_postgres=$(grep "POSTGRES_PASSWORD" /root/postgres.yaml | awk -F '=' '{print $2}')
}

verificar_container_redis() {
    if docker ps -q --filter "name=redis" | grep -q .; then
        return 0
    else
        return 1
    fi
}

verificar_container_minio() {
    if docker ps -q --filter "name=minio" | grep -q .; then
        return 0
    else
        return 1
    fi
}

pegar_senha_minio() {
    user_minio=$(grep "MINIO_ROOT_USER" /root/minio.yaml | awk -F '=' '{print $2}')
    senha_minio=$(grep "MINIO_ROOT_PASSWORD" /root/minio.yaml | awk -F '=' '{print $2}')
    url_minio=$(grep "MINIO_BROWSER_REDIRECT_URL" /root/minio.yaml | awk -F '=' '{print $2}' | sed 's/https:\/\///')
    url_s3=$(grep "MINIO_SERVER_URL" /root/minio.yaml | awk -F '=' '{print $2}' | sed 's/https:\/\///')
}

#########################################################
#
# CHAMANDO NOME DO INSTALADOR + DIREITOS DO INSTALADOR
#

nome_instalador
direitos_instalador

#
#
#
#########################################################
#
# FUNÇÕES COM INSTALAÇÃO DAS APLICAÇÕES
#

wait_for_postgres() {
    dados
    local container_name="postgres"

    echo ""
    while true; do
        CONTAINER_ID=$(docker ps -q --filter "name=.*$container_name.*")

        if [ -n "$CONTAINER_ID" ]; then
            echo ""
            break
        fi

        sleep 5
    done
}

menu_instalador(){

    echo -e "${amarelo}[1]${reset} - ${branco}Traefik & Portainer${reset}"
    echo -e "${amarelo}[2]${reset} - ${branco}Chatwoot${reset}"
    echo -e "${amarelo}[3]${reset} - ${branco}Evolution API${reset}"
    echo -e "${amarelo}[4]${reset} - ${branco}MinIO${reset}"
    echo -e "${amarelo}[5]${reset} - ${branco}Typebot${reset}"
    echo -e "${amarelo}[6]${reset} - ${branco}N8N${reset}"
    echo -e "${amarelo}[7]${reset} - ${branco}Flowise${reset}"
    echo -e "${amarelo}[8]${reset} - ${branco}PgAdmin 4${reset}"
    echo -e "${amarelo}[9]${reset} - ${branco}Nocobase${reset}"
    echo -e "${amarelo}[10]${reset} - ${branco}Botpress${reset}"
    echo -e "${amarelo}[11]${reset} - ${branco}Woofed CRM ${vermelho}[em breve]${reset}"
    echo -e "${amarelo}[12]${reset} - ${branco}Wordpress ${vermelho}[em breve]${reset}"
    echo -e "${amarelo}[13]${reset} - ${branco}Baserow ${vermelho}[em breve]${reset}"
    echo -e "${amarelo}[14]${reset} - ${branco}Jitsi Meet ${vermelho}[em breve]${reset}"
    echo -e "${amarelo}[15]${reset} - ${branco}REMOVER STACK${reset}"
    echo -e "${amarelo}[16]${reset} - ${branco}Sair do instalador${reset}"
    echo ""
}

ferramenta_traefik_e_portainer() {

clear
nome_traefik_e_portainer
preencha_as_info

while true; do
    echo -e "\e[97mPasso$amarelo 1/4\e[0m"
    echo -en "\e[33mDigite o Dominio para o Portainer (ex: portainer.oriondesign.art.br): \e[0m" && read -r url_portainer
    echo ""

    echo -e "\e[97mPasso$amarelo 2/4\e[0m"
    echo -en "\e[33mDigite um nome para seu servidor (ex: OrionDesign): \e[0m" && read -r nome_servidor
    echo ""
    
    echo -e "\e[97mPasso$amarelo 3/4\e[0m"
    echo -en "\e[33mDigite um nome para sua rede interna (ex: OrionNet): \e[0m" && read -r nome_rede_interna
    echo ""
    
    echo -e "\e[97mPasso$amarelo 4/4\e[0m"
    echo -en "\e[33mDigite um endereço de Email valido (ex: orion@oriondesign.art.br): \e[0m" && read -r email_ssl
    echo ""
    

    clear
    nome_traefik_e_portainer
    conferindo_as_info

    echo -e "\e[33mLink do Portainer:\e[97m $url_portainer\e[0m"
    echo ""
    echo -e "\e[33mNome do Servidor:\e[97m $nome_servidor\e[0m"
    echo ""
    echo -e "\e[33mRede interna:\e[97m $nome_rede_interna\e[0m"
    echo ""
    echo -e "\e[33mEmail para SSL:\e[97m $email_ssl\e[0m"
    echo ""
    echo ""

    read -p "As respostas estão corretas? (Y/N): " confirmacao
    if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
        clear
        instalando_msg
        break
    else
        clear
        nome_traefik_e_portainer
        preencha_as_info
    fi
done

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/6]\e[0m"
echo ""
sleep 3

#SALVANDO DADOS NA VPS
cd
cd
mkdir dados_vps
cd dados_vps
cat > dados_vps << EOL
[DADOS DA VPS]

Estes dados foram preenchidos na hora que você foi instalar o Traefik e Portainer e
serão utilizados para realizar as instalações no do SetupOrion v.2

Nome do Servidor: $nome_servidor

Rede interna: $nome_rede_interna

Email para SSL: $email_ssl

Link do Portainer: $url_portainer

Obrigado por utilizar nosso AutoInstalador.
Caso esse conteudo foi util, não deixe de apoiar nosso projeto.

pix@oriondesign.art.br

Bebam água!
EOL

cd
cd

#PEGANDO DADOS DA VPS
dados

#AUTALIZANDO VPS
sudo apt-get update > /dev/null

sudo apt upgrade -y > /dev/null 2>&1

#DEFININDO TIMEZONE
sudo timedatectl set-timezone America/Sao_Paulo

sudo apt-get update > /dev/null

#MENSAGEM DE CONFIGURANDO A VPS (PASSOS)
echo -e "\e[97m• CONFIGURANDO A VPS \e[33m[2/6]\e[0m"
echo ""

#CONFIGURANDO VPS
hostnamectl set-hostname $nome_servidor > /dev/null

sudo sed -i "s/127.0.0.1[[:space:]]localhost/127.0.0.1 $nome_servidor/g" /etc/hosts > /dev/null 2>&1

sudo apt-get update > /dev/null

#INSTALANDO AS DEPENDENCIAS
sudo apt-get install -y apparmor-utils > /dev/null

#MENSAGEM DE INSTALANDO DOCKER (PASSOS)
echo -e "\e[97m• INSTALANDO DOCKER SWARN \e[33m[3/6]\e[0m"
echo ""

#INSTALANDO DOCKER SWARM
curl -fsSL https://get.docker.com | bash > /dev/null 2>&1

docker swarm init > /dev/null

#MENSAGEM DE CRIANDO REDE INTERNA (PASSOS)
echo -e "\e[97m• CRIANDO REDE INTERNA \e[33m[4/6]\e[0m"
echo ""


#CRIANDO REDE INTERNA
docker network create --driver=overlay $nome_rede_interna > /dev/null

#MENSAGEM DE INSTALANDO TRAEFIK (PASSOS)
echo -e "\e[97m• INSTALANDO TRAEFIK \e[33m[5/6]\e[0m"
echo ""

# CRIANDO ARQUIVO DO TRAEFIK

cat > traefik.yaml << EOL
version: "3.7"

services:

  traefik:
    image: traefik:latest
    command:
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=$nome_rede_interna"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencryptresolver.acme.email=$email_ssl"
      - "--log.level=DEBUG"
      - "--log.format=common"
      - "--log.filePath=/var/log/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access-log"
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
        - "traefik.http.routers.http-catchall.rule=Host(\`{host:.+}\`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=redirect-https@docker"
        - "traefik.http.routers.http-catchall.priority=1"
    volumes:
      - "vol_certificates:/etc/traefik/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - $nome_rede_interna

volumes:

  vol_shared:
    external: true
    name: volume_swarm_shared
  vol_certificates:
    external: true
    name: volume_swarm_certificates

networks:

  $nome_rede_interna:
    external: true
    name: $nome_rede_interna
EOL

#SUBINDO STACK DO TREAFIK
docker stack deploy --prune --resolve-image always -c traefik.yaml traefik > /dev/null 2>&1

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço trarik está ativo
    if docker service ls --filter "name=traefik" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#MENSAGEM DE INSTALANDO PORTAINER (PASSOS)
echo -e "\e[97m• INSTALANDO PORTAINER \e[33m[6/6]\e[0m"
echo ""

#GERANDO SENHA
#gerador_de_senha_traefik
#command: --admin-password '$senha'

#CRIANDO ARQUIVO DO PORTAINER
cat > portainer.yaml <<EOL
version: "3.7"

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - $nome_rede_interna
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - $nome_rede_interna
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(\`$url_portainer\`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.docker.network=$nome_rede_interna"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.priority=1"

networks:
  $nome_rede_interna:
    external: true
    attachable: true
    name: $nome_rede_interna

volumes:
  portainer_data:
    external: true
    name: portainer_data
EOL

#SUBINDO STACK DO PORTAINER
docker stack deploy --prune --resolve-image always -c portainer.yaml portainer > /dev/null 2>&1

sleep 5

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço portainer está ativo
    if docker service ls --filter "name=portainer" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[PORTAINER]\e[0m"
echo ""
echo -e "\e[97mDominio:\e[33m https://$url_portainer\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi

}

ferramenta_postgres() {
#PEGANDO DADOS DA VPS
dados

#GERANDO SENHA
senha_postgres=$(openssl rand -hex 16)

#CRIANDO ARQUIVO DO POSTGRES
cat > postgres.yaml <<EOL
version: "3.7"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=$senha_postgres
    networks:
      - $nome_rede_interna
    #ports:
    #  - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna
EOL

#SUBINDO STACK DO POSTGRES
docker stack deploy --prune --resolve-image always -c postgres.yaml postgres

sleep 10
}

criar_banco_postgres_chatwoot() {
    
    while :; do
        if docker ps -q --filter "name=postgres" | grep -q .; then
            CONTAINER_ID=$(docker ps -q --filter "name=postgres")
            docker exec -it "$CONTAINER_ID" psql -U postgres -c "CREATE DATABASE chatwoot;"
            break
        else
            sleep 5
        fi
    done
}

criar_banco_postgres_n8n() {
    
    while :; do
        if docker ps -q --filter "name=postgres" | grep -q .; then
            CONTAINER_ID=$(docker ps -q --filter "name=postgres")
            docker exec -it "$CONTAINER_ID" psql -U postgres -c "CREATE DATABASE n8n_queue;"
            sleep 2
            break
        else
            sleep 5
        fi
    done
}

criar_banco_postgres_typebot() {
    
    while :; do
        if docker ps -q --filter "name=postgres" | grep -q .; then
            CONTAINER_ID=$(docker ps -q --filter "name=postgres")
            docker exec -it "$CONTAINER_ID" psql -U postgres -c "CREATE DATABASE typebot;"
            break
        else
            sleep 5
        fi
    done
}

criar_banco_postgres_flowise() {
    
    while :; do
        if docker ps -q --filter "name=postgres" | grep -q .; then
            CONTAINER_ID=$(docker ps -q --filter "name=postgres")
            docker exec -it "$CONTAINER_ID" psql -U postgres -c "CREATE DATABASE flowise;"
            break
        else
            sleep 5
        fi
    done
}

criar_banco_postgres_nocobase() {

    while :; do
    if docker ps -q --filter "name=postgres" | grep -q .; then
        CONTAINER_ID=$(docker ps -q --filter "name=postgres")


        docker exec -it "$CONTAINER_ID" psql -U postgres -c "CREATE DATABASE nocobase;"

        docker exec -it "$CONTAINER_ID" psql -U postgres -d nocobase -c "GRANT ALL PRIVILEGES ON DATABASE nocobase TO postgres;"

        break
    else
        sleep 5
    fi
done

}

criar_banco_postgres_botpress() {
    while :; do
        if docker ps -q --filter "name=postgres" | grep -q .; then
            CONTAINER_ID=$(docker ps -q --filter "name=postgres")
            docker exec -it "$CONTAINER_ID" psql -U postgres -c "CREATE DATABASE botpress;"
            break
        else
            sleep 5
        fi
    done
}

ferramenta_redis() {
#PEGANDO DADOS DA VPS
dados

#CRIANDO ARQUIVO DO REDIS
cat > redis.yaml <<EOL
version: "3.7"

services:
  redis:
    image: redis:latest
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]
    volumes:
      - redis_data:/data
    networks:
      - $nome_rede_interna
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna
EOL

#SUBINDO STACK DO REDIS
docker stack deploy --prune --resolve-image always -c redis.yaml redis

sleep 10
}

ferramenta_minio() {
clear
dados
nome_minio
preencha_as_info

while true; do
  
echo -e "\e[97mPasso$amarelo 1/4\e[0m"
echo -en "\e[33mDigite o Dominio para o MinIO: \e[0m" && read -r url_minio
echo ""

echo -e "\e[97mPasso$amarelo 2/4\e[0m"
echo -en "\e[33mDigite o Dominio para o Minio S3: \e[0m" && read -r url_s3
echo ""

echo -e "\e[97mPasso$amarelo 3/4\e[0m"
echo -en "\e[33mDigite um usuario para o MinIO: \e[0m" && read -r user_minio
echo ""

echo -e "\e[97mPasso$amarelo 4/4\e[0m"
echo -en "\e[33mDigite uma senha para o MinIO: \e[0m" && read -r senha_minio
echo ""

clear
    nome_minio
    conferindo_as_info

    echo -e "\e[33mDominio do MinIO:\e[97m $url_minio\e[0m"
    echo ""

    echo -e "\e[33mDominio para o Minio S3:\e[97m $url_s3\e[0m"
    echo ""

    echo -e "\e[33mUsuario para o MinIO:\e[97m $user_minio\e[0m"
    echo ""    

    echo -e "\e[33mSenha para o MinIO:\e[97m $senha_minio\e[0m"
    echo ""

    read -p "As respostas estão corretas? (Y/N): " confirmacao
    if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
        clear
        instalando_msg
        break
    else
        clear
        nome_minio
        preencha_as_info
    fi
    done

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/2]\e[0m"
echo ""
sleep 3

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INSTALANDO MINIO \e[33m[2/2]\e[0m"
echo ""

#CRIANDO ARQUIVO DO MINIO
cat > minio.yaml <<EOL
version: "3.7"

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    networks:
      - $nome_rede_interna
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=$user_minio
      - MINIO_ROOT_PASSWORD=$senha_minio
      - MINIO_BROWSER_REDIRECT_URL=https://$url_minio
      - MINIO_SERVER_URL=https://$url_s3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio_public.rule=Host(\`$url_s3\`)
        - traefik.http.routers.minio_public.entrypoints=websecure
        - traefik.http.routers.minio_public.tls.certresolver=letsencryptresolver
        - traefik.http.services.minio_public.loadbalancer.server.port=9000
        - traefik.http.services.minio_public.loadbalancer.passHostHeader=true
        - traefik.http.routers.minio_public.service=minio_public
        - traefik.http.routers.minio_console.rule=Host(\`$url_minio\`)
        - traefik.http.routers.minio_console.entrypoints=websecure
        - traefik.http.routers.minio_console.tls.certresolver=letsencryptresolver
        - traefik.http.services.minio_console.loadbalancer.server.port=9001
        - traefik.http.services.minio_console.loadbalancer.passHostHeader=true
        - traefik.http.routers.minio_console.service=minio_console
volumes:
  minio_data:
    external: true
    name: minio_data

networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna
EOL

#SUBINDO STACK DO MINIO
docker stack deploy --prune --resolve-image always -c minio.yaml minio

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço minio está ativo
    if docker service ls --filter "name=minio" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[MinIO]\e[0m"
echo ""
echo -e "\e[33mDominio:\e[97m https://$url_minio\e[0m"
echo ""
echo -e "\e[33mUsuario:\e[97m $user_minio\e[0m"
echo ""    
echo -e "\e[33mSenha:\e[97m $senha_minio\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi
}

ferramenta_chatwoot() {

    nome_chatwoot
    preencha_as_info

    while true; do

    echo -e "\e[97mPasso$amarelo 1/5\e[0m"
    echo -en "\e[33mDigite o Dominio para o Chatwoot (ex: app.oriondesign.art.br): \e[0m" && read -r url_chatwoot
    echo ""

    #echo -e "\e[97mPasso$amarelo 2/6$branco - Configurando Chatwoot\e[0m"
    #echo -en "\e[33mDigite o nome da sua Empresa: \e[0m" && read -r nome_empresa_chatwoot
    #echo ""
    nome_empresa_chatwoot="$nome_servidor"

    echo -e "\e[97mPasso$amarelo 2/5\e[0m"
    echo -en "\e[33mDigite o Email de Administrador: \e[0m" && read -r email_admin_chatwoot
    echo ""

    echo -e "\e[97mPasso$amarelo 3/5\e[0m"
    echo -en "\e[33mDigite a Senha do Email: \e[0m" && read -r senha_email_chatwoot
    echo ""

    dominio_smtp_chatwoot=$(echo "$email_admin_chatwoot" | cut -d "@" -f 2)

    echo -e "\e[97mPasso$amarelo 4/5\e[0m"
    echo -en "\e[33mDigite o Host SMTP do Email: \e[0m" && read -r smtp_email_chatwoot
    echo ""

    echo -e "\e[97mPasso$amarelo 5/5\e[0m"
    echo -en "\e[33mDigite a porta SMTP do Email: \e[0m" && read -r porta_smtp_chatwoot
    
    clear
    nome_chatwoot
    conferindo_as_info

    echo -e "\e[33mDominio do Chatwoot:\e[97m $url_chatwoot\e[0m"
    echo ""
    echo -e "\e[33mNome da Empresa:\e[97m $nome_empresa_chatwoot\e[0m"
    echo ""
    echo -e "\e[33mEmail de Administrador:\e[97m $email_admin_chatwoot\e[0m"
    echo ""
    echo -e "\e[33mSenha do Email:\e[97m $senha_email_chatwoot\e[0m"
    echo ""
    echo -e "\e[33mHost SMTP:\e[97m $smtp_email_chatwoot\e[0m"
    echo ""
    echo -e "\e[33mPorta SMTP:\e[97m $porta_smtp_chatwoot\e[0m"
    echo ""
    echo ""

    read -p "As respostas estão corretas? (Y/N): " confirmacao
    if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
        clear
        instalando_msg
        break
    else
        clear
        nome_chatwoot
        preencha_as_info
    fi
    done



#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/4]\e[0m"
echo ""

    dados

    verificar_container_postgres
    if [ $? -eq 0 ]; then
        echo ""
        pegar_senha_postgres > /dev/null 2>&1
        criar_banco_postgres_chatwoot > /dev/null 2>&1
    else
        ferramenta_postgres > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1
        criar_banco_postgres_chatwoot > /dev/null 2>&1
    fi

    verificar_container_redis
    if [ $? -eq 0 ]; then
        echo ""
    else
        ferramenta_redis > /dev/null 2>&1
    fi

#MENSAGEM DE INSTALANDO CHATWOOT (PASSOS)
echo -e "\e[97m• INSTALANDO CHATWOOT \e[33m[2/4]\e[0m"
echo ""

encryption_key=$(openssl rand -hex 16)

cat > chatwoot.yaml <<EOL
version: "3.7"

services:
  chatwoot_app:
    image: chatwoot/chatwoot:latest
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - chatwoot_data:/app/storage
      - chatwoot_public_orion:/app/public 
    networks:
      - $nome_rede_interna
    environment:
      - INSTALLATION_NAME=$nome_empresa_chatwoot
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=$encryption_key
      - FRONTEND_URL=https://$url_chatwoot
      - DEFAULT_LOCALE=pt_BR
      - FORCE_SSL=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=$senha_postgres
      - POSTGRES_DATABASE=chatwoot
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - MAILER_SENDER_EMAIL=$email_admin_chatwoot <$email_admin_chatwoot>
      - SMTP_DOMAIN=$dominio_smtp_chatwoot
      - SMTP_ADDRESS=$smtp_email_chatwoot
      - SMTP_PORT=$porta_smtp_chatwoot
      - SMTP_USERNAME=$email_admin_chatwoot
      - SMTP_PASSWORD=$senha_email_chatwoot
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=$email_admin_chatwoot
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_app.rule=Host(\`$url_chatwoot\`)
        - traefik.http.routers.chatwoot_app.entrypoints=websecure
        - traefik.http.routers.chatwoot_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot_app.priority=1
        - traefik.http.routers.chatwoot_app.service=chatwoot_app
        - traefik.http.services.chatwoot_app.loadbalancer.server.port=3000 
        - traefik.http.services.chatwoot_app.loadbalancer.passhostheader=true 
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=sslheader@docker

  chatwoot_sidekiq:
    image: chatwoot/chatwoot:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_data:/app/storage
      - chatwoot_public_orion:/app/public
    networks:
      - $nome_rede_interna
    environment:
      - INSTALLATION_NAME=$nome_empresa_chatwoot
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=$encryption_key
      - FRONTEND_URL=https://$url_chatwoot
      - DEFAULT_LOCALE=pt_BR
      - FORCE_SSL=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=$senha_postgres
      - POSTGRES_DATABASE=chatwoot
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - MAILER_SENDER_EMAIL=$email_admin_chatwoot <$email_admin_chatwoot>
      - SMTP_DOMAIN=$dominio_smtp_chatwoot
      - SMTP_ADDRESS=$smtp_email_chatwoot
      - SMTP_PORT=$porta_smtp_chatwoot
      - SMTP_USERNAME=$email_admin_chatwoot
      - SMTP_PASSWORD=$senha_email_chatwoot
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=$email_admin_chatwoot
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  chatwoot_data:
    external: true
    name: chatwoot_data
  chatwoot_public_orion:
    external: true
    name: chatwoot_public_orion

networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna
EOL

#SUBINDO STACK DO CHATWOOT
docker stack deploy --prune --resolve-image always -c chatwoot.yaml chatwoot > /dev/null 2>&1

sleep 10
#MENSAGEM DE MIGRANDO BANCO DE DADOS (PASSOS)
echo -e "\e[97m• MIGRANDO BANCO DE DADOS \e[33m[3/4]\e[0m"
echo ""

#MIGRANDO BANCO DE DADOS DO CHATWOOT
container_name="chatwoot_chatwoot_app"

max_wait_time=600

wait_interval=60

elapsed_time=0

while [ $elapsed_time -lt $max_wait_time ]; do
  CONTAINER_ID=$(docker ps -q --filter "name=$container_name")
  if [ -n "$CONTAINER_ID" ]; then
    break
  fi
  sleep $wait_interval
  elapsed_time=$((elapsed_time + wait_interval))
done

if [ -z "$CONTAINER_ID" ]; then
  echo "O contêiner não foi encontrado após $max_wait_time segundos."
  exit 1
fi

docker exec -it "$CONTAINER_ID" bundle exec rails db:chatwoot_prepare

#MENSAGEM DE ATIVANDO FUNÇÕES DO SUPER ADMIN (PASSOS)
echo -e "\e[97m• ATIVANDO FUNÇÕES DO SUPER ADMIN \e[33m[4/4]\e[0m"
echo ""

#HABILITANDO FUNÇÕES DO SUPER ADMIN
wait_for_postgres

docker exec -i $CONTAINER_ID psql -U postgres <<EOF
\c chatwoot;
update installation_configs set locked = false;
\q
EOF

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço chatwoot está ativo
    if docker service ls --filter "name=chatwoot" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[CHATWOOT]\e[0m"
echo ""
echo -e "\e[97mDominio:\e[33m https://$url_chatwoot\e[0m"
echo ""
echo -e "\e[97mEmail:\e[33m $email_admin_chatwoot\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi

}

ferramenta_evolution() {
dados

clear
nome_evolution
preencha_as_info

while true; do

    echo -e "\e[97mPasso$amarelo 1/1\e[0m"
    echo -en "\e[33mDigite o Dominio para a Evolution API (ex: api.oriondesign.art.br): \e[0m" && read -r url_evolution
    echo ""
    
    clear
    nome_evolution
    conferindo_as_info

    echo -e "\e[33mDominio da Evolution API:\e[97m $url_evolution\e[0m"
    echo ""

    read -p "As respostas estão corretas? (Y/N): " confirmacao
    if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
        clear
        instalando_msg
        break
    else
        clear
        nome_evolution
        preencha_as_info
    fi
    done

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/3]\e[0m"
echo ""
sleep 3

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INSTALANDO EVOLUTION API \e[33m[2/3]\e[0m"
echo ""

#CRIANDO ARQUIVO DA EVOLUTION API
apikeyglobal=$(openssl rand -hex 16)

cat > evolution.yaml <<EOL
version: "3.7"
services:
  evolution_oriondesign:
    image: davidsongomes/evolution-api:latest
    command: ["node", "./dist/src/main.js"]
    volumes:
    - evolution_oriondesign_instances:/evolution/instances
    - evolution_oriondesign_store:/evolution/store
    - evolution_oriondesign_views:/evolution/views
    networks:
      - $nome_rede_interna
    environment:
    - SERVER_URL=https://$url_evolution 
    - DOCKER_ENV=true
    - LOG_LEVEL=ERROR
    - DEL_INSTANCE=false
    - CONFIG_SESSION_PHONE_CLIENT=OrionDesign
    - CONFIG_SESSION_PHONE_NAME=chrome
    - STORE_MESSAGES=true
    - STORE_MESSAGE_UP=true
    - STORE_CONTACTS=true
    - STORE_CHATS=true
    - CLEAN_STORE_CLEANING_INTERVAL=7200 # seconds === 2h
    - CLEAN_STORE_MESSAGES=true
    - CLEAN_STORE_MESSAGE_UP=true
    - CLEAN_STORE_CONTACTS=true
    - CLEAN_STORE_CHATS=true
    - AUTHENTICATION_TYPE=apikey
    - AUTHENTICATION_API_KEY=$apikeyglobal
    - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
    - QRCODE_LIMIT=19021
    - WEBHOOK_GLOBAL_ENABLED=false
    - WEBHOOK_GLOBAL_URL=https://URL
    - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
    - WEBHOOK_EVENTS_APPLICATION_STARTUP=false
    - WEBHOOK_EVENTS_QRCODE_UPDATED=true
    - WEBHOOK_EVENTS_MESSAGES_SET=false
    - WEBHOOK_EVENTS_MESSAGES_UPSERT=true
    - WEBHOOK_EVENTS_MESSAGES_UPDATE=true
    - WEBHOOK_EVENTS_CONTACTS_SET=true
    - WEBHOOK_EVENTS_CONTACTS_UPSERT=true
    - WEBHOOK_EVENTS_CONTACTS_UPDATE=true
    - WEBHOOK_EVENTS_PRESENCE_UPDATE=true
    - WEBHOOK_EVENTS_CHATS_SET=true
    - WEBHOOK_EVENTS_CHATS_UPSERT=true
    - WEBHOOK_EVENTS_CHATS_UPDATE=true
    - WEBHOOK_EVENTS_CHATS_DELETE=true
    - WEBHOOK_EVENTS_GROUPS_UPSERT=true
    - WEBHOOK_EVENTS_GROUPS_UPDATE=true
    - WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE=true
    - WEBHOOK_EVENTS_CONNECTION_UPDATE=true
    - REDIS_ENABLED=false
    - REDIS_URI=redis://redis:6379
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=1
      - traefik.http.routers.evolution_oriondesign.rule=Host(\`$url_evolution\`)
      - traefik.http.routers.evolution_oriondesign.entrypoints=websecure
      - traefik.http.routers.evolution_oriondesign.priority=1
      - traefik.http.routers.evolution_oriondesign.tls.certresolver=letsencryptresolver
      - traefik.http.routers.evolution_oriondesign.service=evolution_oriondesign
      - traefik.http.services.evolution_oriondesign.loadbalancer.server.port=8080
      - traefik.http.services.evolution_oriondesign.loadbalancer.passHostHeader=1
volumes:
  evolution_oriondesign_instances:
    external: true
    name: evolution_oriondesign_instances
  evolution_oriondesign_store:
    external: true
    name: evolution_oriondesign_store
  evolution_oriondesign_views:
    external: true
    name: evolution_oriondesign_views
networks:
  $nome_rede_interna:
    name: $nome_rede_interna
    external: true
EOL

#SUBINDO STACK DA EVOLUTION API

docker stack deploy --prune --resolve-image always -c evolution.yaml evolution > /dev/null 2>&1

sleep 10
#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INSERINDO MANAGER NA API \e[33m[3/3]\e[0m"
echo ""

# INSERINDO O MANAGER NA EVOLUTION
while true
do
   
    if [ -f "/var/lib/docker/volumes/evolution_oriondesign_views/_data/manager.hbs" ]
    then
        
        sed -i 's|https://manager.evolution-api.com|https://app.appsmith.com/app/novo-manager/home-65259b67441fc2031cd34918|' /var/lib/docker/volumes/evolution_oriondesign_views/_data/manager.hbs 
        
        #docker stack deploy --prune --resolve-image always -c evolution.yaml evolution 
        docker stack deploy --resolve-image always --prune --force -c evolution.yaml evolution > /dev/null 2>&1
  
        break
    else
        sleep 5
    fi
done

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço evolution está ativo
    if docker service ls --filter "name=evolution" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[Evolution API]\e[0m"
echo ""
echo -e "\e[97mLink do Manager:\e[33m https://$url_evolution/manager\e[0m"
echo ""
echo -e "\e[97mAPI URL:\e[33m https://$url_evolution\e[0m"
echo ""
echo -e "\e[97mGLOBAL API KEY:\e[33m $apikeyglobal\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi

}

ferramenta_typebot() {
clear
dados
nome_typebot
preencha_as_info

#Verificando MINIO
verificar_container_minio
if [ $? -eq 0 ]; then
        echo ""
        pegar_senha_minio > /dev/null 2>&1
    else
        echo "Observação, é necessario instalar o MINIO antes de continuar a instalarção do Typebot"
        echo "Encerrando o instalador em 5 segundos"
        sleep 5
        exit
fi

while true; do

    echo -e "\e[97mPasso$amarelo 1/9\e[0m"
    echo -en "\e[33mDigite o Dominio para o Builder do Typebot (ex: typebot.oriondesign.art.br): \e[0m" && read -r url_typebot
    echo ""

    echo -e "\e[97mPasso$amarelo 2/9\e[0m"
    echo -en "\e[33mDigite o Dominio para o Viewer do Typebot (ex: bot.oriondesign.art.br): \e[0m" && read -r url_viewer
    echo ""

    echo -e "\e[97mPasso$amarelo 3/9\e[0m"
    echo -en "\e[33mDigite a versão que deseja do Typebot (ex: 2.19.0 ou latest): \e[0m" && read -r versao_typebot
    echo ""

    echo -e "\e[97mPasso$amarelo 4/9\e[0m"
    echo -en "\e[33mDigite o Email de admin: (ex: contato@oriondesign.art.br): \e[0m" && read -r email_typebot
    echo ""
    
    echo -e "\e[97mPasso$amarelo 5/9\e[0m"
    echo -en "\e[33mDigite a Senha do email: \e[0m" && read -r senha_email_typebot
    echo ""

    echo -e "\e[97mPasso$amarelo 6/9\e[0m"
    echo -en "\e[33mDigite o HOST SMTP do email (ex: smtp.hostinger.com): \e[0m" && read -r smtp_email_typebot
    echo ""

    echo -e "\e[97mPasso$amarelo 7/9\e[0m"
    echo -en "\e[33mDigite a Porta SMTP do email: \e[0m" && read -r porta_smtp_typebot
    echo ""

    echo -e "\e[97mPasso$amarelo 8/9\e[0m"
    echo -en "\e[33mAccess Key Minio: \e[0m" && read -r S3_ACCESS_KEY
    echo ""

    echo -e "\e[97mPasso$amarelo 9/9\e[0m"
    echo -en "\e[33mSecret Key Minio: \e[0m" && read -r S3_SECRET_KEY
    echo ""

    if [ "$porta_smtp_typebot" -eq 465 ]; then
    smtp_secure_typebot=true
    else
    smtp_secure_typebot=false
    fi
    
    clear
    nome_typebot
    conferindo_as_info

    echo -e "\e[33mDominio do Typebot Builder:\e[97m $url_typebot\e[0m"
    echo ""

    echo -e "\e[33mDominio do Typebot Viewer:\e[97m $url_viewer\e[0m"
    echo ""

    echo -e "\e[33mVersão do Typebot:\e[97m $versao_typebot\e[0m"
    echo ""    

    echo -e "\e[33mEmail de Admin:\e[97m $email_typebot\e[0m"
    echo ""

    echo -e "\e[33mSenha do Email:\e[97m $senha_email_typebot\e[0m"
    echo ""

    echo -e "\e[33mHost SMTP do Email:\e[97m $smtp_email_typebot\e[0m"
    echo ""

    echo -e "\e[33mPorta SMTP do Email:\e[97m $porta_smtp_typebot\e[0m"
    echo ""

    echo -e "\e[33mSecure SMTP do Email:\e[97m $smtp_secure_typebot\e[0m"
    echo ""

    echo -e "\e[33mAccess Key Minio:\e[97m $S3_ACCESS_KEY\e[0m"
    echo ""

    echo -e "\e[33mSecret Key Minio:\e[97m $S3_SECRET_KEY\e[0m"
    echo ""

    read -p "As respostas estão corretas? (Y/N): " confirmacao
    if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
        clear
        instalando_msg
        break
    else
        clear
        nome_typebot
        preencha_as_info
    fi
    done

#VERIFICAR POSTGRES

echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/3]\e[0m"
echo ""

echo -e "\e[97m• VERIFICANDO E/OU INSTALANDO POSTGRES \e[33m[2/3]\e[0m"
echo ""

verificar_container_postgres
if [ $? -eq 0 ]; then
        echo ""
        criar_banco_postgres_typebot > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1
    else
        ferramenta_postgres > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1
        criar_banco_postgres_typebot > /dev/null 2>&1
fi

echo -e "\e[97m• INSTALANDO TYPEBOT \e[33m[3/3]\e[0m"
echo ""

#CRIANDO ARQUIVO DO BUILDER DO TYPEBOT
key_typebot=$(openssl rand -hex 16)

cat > typebot.yaml <<EOL
version: "3.7"

services:
  typebot_builder:
    image: baptistearno/typebot-builder:$versao_typebot
    networks:
      - $nome_rede_interna
    environment:
      - DATABASE_URL=postgresql://postgres:$senha_postgres@postgres:5432/typebot
      - ENCRYPTION_SECRET=2652c632beb3f7c3fa800ce3eb022ce4
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - NEXTAUTH_URL=https://$url_typebot
      - NEXT_PUBLIC_VIEWER_URL=https://$url_viewer
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - DISABLE_SIGNUP=false
      - ADMIN_EMAIL=$email_typebot
      - NEXT_PUBLIC_SMTP_FROM='Suporte' <$email_typebot>
      - SMTP_AUTH_DISABLED=false
      - SMTP_USERNAME=$email_typebot
      - SMTP_PASSWORD=$senha_email_typebot
      - SMTP_HOST=$smtp_email_typebot
      - SMTP_PORT=$porta_smtp_typebot
      - SMTP_SECURE=$smtp_secure_typebot

      ### Google Cloud ###
      #
      #- GOOGLE_CLIENT_ID=
      #- GOOGLE_CLIENT_SECRET=
      #
      ####################

      - S3_ACCESS_KEY=$S3_ACCESS_KEY
      - S3_SECRET_KEY=$S3_SECRET_KEY
      - S3_BUCKET=typebot
      - S3_ENDPOINT=$url_s3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - io.portainer.accesscontrol.users=admin
        - traefik.enable=true
        - traefik.http.routers.typebot_builder.rule=Host(\`$url_typebot\`)
        - traefik.http.routers.typebot_builder.entrypoints=websecure
        - traefik.http.routers.typebot_builder.tls.certresolver=letsencryptresolver
        - traefik.http.services.typebot_builder.loadbalancer.server.port=3000
        - traefik.http.services.typebot_builder.loadbalancer.passHostHeader=true
        - traefik.http.routers.typebot_builder.service=typebot_builder

################################################################################

  typebot_viewer:
    image: baptistearno/typebot-viewer:$versao_typebot
    networks:
      - $nome_rede_interna
    environment:
      - DATABASE_URL=postgresql://postgres:$senha_postgres@postgres:5432/typebot
      - ENCRYPTION_SECRET=2652c632beb3f7c3fa800ce3eb022ce4
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - NEXTAUTH_URL=https://$url_typebot
      - NEXT_PUBLIC_VIEWER_URL=https://$url_viewer
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - DISABLE_SIGNUP=false
      - ADMIN_EMAIL=$email_typebot
      - NEXT_PUBLIC_SMTP_FROM='Suporte' <$email_typebot>
      - SMTP_AUTH_DISABLED=false
      - SMTP_USERNAME=$email_typebot
      - SMTP_PASSWORD=$senha_email_typebot
      - SMTP_HOST=$smtp_email_typebot
      - SMTP_PORT=$porta_smtp_typebot
      - SMTP_SECURE=$smtp_secure_typebot

      ### Google Cloud ###
      #
      #- GOOGLE_CLIENT_ID=
      #- GOOGLE_CLIENT_SECRET=
      #
      ####################

      - S3_ACCESS_KEY=$S3_ACCESS_KEY
      - S3_SECRET_KEY=$S3_SECRET_KEY
      - S3_BUCKET=typebot
      - S3_ENDPOINT=$url_s3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - io.portainer.accesscontrol.users=admin
        - traefik.enable=true
        - traefik.http.routers.typebot_viewer.rule=Host(\`$url_viewer\`)
        - traefik.http.routers.typebot_viewer.entrypoints=websecure
        - traefik.http.routers.typebot_viewer.tls.certresolver=letsencryptresolver
        - traefik.http.services.typebot_viewer.loadbalancer.server.port=3000
        - traefik.http.services.typebot_viewer.loadbalancer.passHostHeader=true
        - traefik.http.routers.typebot_viewer.service=typebot_viewer

networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna

EOL

#SUBINDO STACK DO TYPEBOT
docker stack deploy --prune --resolve-image always -c typebot.yaml typebot > /dev/null 2>&1

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço typebot está ativo
    if docker service ls --filter "name=typebot" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[Typebot]\e[0m"
echo ""
echo -e "\e[33mDominio:\e[97m https://$url_typebot\e[0m"
echo ""
echo -e "\e[33mEmail:\e[97m $email_typebot\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi
}

ferramenta_n8n() {
dados
clear
nome_n8n
preencha_as_info

while true; do

echo -e "\e[97mPasso$amarelo 1/2\e[0m"
echo -en "\e[33mDigite o dominio para o N8N (ex: n8n.oriondesign.art.br): \e[0m" && read -r url_editorn8n
echo ""

echo -e "\e[97mPasso$amarelo 2/2\e[0m"
echo -en "\e[33mDigite o dominio para o Webhook do N8N (ex: webhookn8n.oriondesign.art.br): \e[0m" && read -r url_webhookn8n
echo ""
    
clear
nome_n8n
conferindo_as_info

echo -e "\e[33mDominio do N8N\e[97m $url_editorn8n\e[0m"
echo ""

echo -e "\e[33mDominio do Webhook do N8N:\e[97m $url_webhookn8n\e[0m"
echo ""

read -p "As respostas estão corretas? (Y/N): " confirmacao
if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
    clear
    instalando_msg
    break
else
    clear
    nome_n8n
    preencha_as_info
fi
done

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/3]\e[0m"
echo ""
sleep 3

echo -e "\e[97m• VERIFICANDO/INSTALANDO POSTGRES \e[33m[2/3]\e[0m"
echo ""

verificar_container_postgres
if [ $? -eq 0 ]; then
        echo ""
        criar_banco_postgres_n8n > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1

    else
        ferramenta_postgres > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1
        criar_banco_postgres_n8n > /dev/null 2>&1
fi


echo -e "\e[97m• INSTALANDO N8N \e[33m[3/3]\e[0m"
echo ""
sleep 3

#CRIANDO ARQUIVO DO N8N
encryption_key=$(openssl rand -hex 16)

cat > n8n.yaml <<EOL
version: "3.7"

services:
  n8n_editor:
    image: n8nio/n8n:latest
    command: start
    networks:
      - $nome_rede_interna
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=$senha_postgres
      - N8N_ENCRYPTION_KEY=$encryption_key
      - N8N_HOST=$url_editorn8n
      - N8N_EDITOR_BASE_URL=https://$url_editorn8n/
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://$url_webhookn8n/
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_editor.rule=Host(\`$url_editorn8n\`)
        - traefik.http.routers.n8n_editor.entrypoints=websecure
        - traefik.http.routers.n8n_editor.priority=1
        - traefik.http.routers.n8n_editor.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_editor.service=n8n_editor
        - traefik.http.services.n8n_editor.loadbalancer.server.port=5678
        - traefik.http.services.n8n_editor.loadbalancer.passHostHeader=1

  n8n_webhook:
    image: n8nio/n8n:latest
    command: webhook
    networks:
      - $nome_rede_interna
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=$senha_postgres
      - N8N_ENCRYPTION_KEY=$encryption_key
      - N8N_HOST=$url_editorn8n
      - N8N_EDITOR_BASE_URL=https://$url_editorn8n/
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://$url_webhookn8n/
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_webhook.rule=(Host(\`$url_webhookn8n\`))
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_webhook.priority=1
        - traefik.http.routers.n8n_webhook.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678
        - traefik.http.services.n8n_webhook.loadbalancer.passHostHeader=1

  n8n_worker:
    image: n8nio/n8n:latest
    command: worker --concurrency=10
    networks:
      - $nome_rede_interna
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=$senha_postgres
      - N8N_ENCRYPTION_KEY=$encryption_key
      - N8N_HOST=$url_editorn8n
      - N8N_EDITOR_BASE_URL=https://$url_editorn8n/
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://$url_webhookn8n/
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

networks:
  $nome_rede_interna:
    name: $nome_rede_interna
    external: true
EOL

#SUBINDO STACK DO N8N
docker stack deploy --prune --resolve-image always -c n8n.yaml n8n > /dev/null 2>&1


#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço n8n está ativo
    if docker service ls --filter "name=n8n" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[N8N]\e[0m"
echo ""
echo -e "\e[33mDominio:\e[97m https://$url_editorn8n\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi
}

ferramenta_flowise() {

dados
clear
nome_flowise
preencha_as_info

while true; do

echo -e "\e[97mPasso$amarelo 1/3\e[0m"
echo -en "\e[33mDigite o dominio para o N8N (ex: flowise.oriondesign.art.br): \e[0m" && read -r url_flowise
echo ""

echo -e "\e[97mPasso$amarelo 2/3\e[0m"
echo -en "\e[33mDigite um usuario para o Flowise (ex: admin): \e[0m" && read -r user_flowise
echo ""

echo -e "\e[97mPasso$amarelo 3/3\e[0m"
echo -en "\e[33mDigite uma senha para o usuario (ex: @Senha123_): \e[0m" && read -r pass_flowise
echo ""

clear
nome_flowise
conferindo_as_info

echo -e "\e[33mDominio do Flowise\e[97m $url_flowise\e[0m"
echo ""

echo -e "\e[33mUsuario:\e[97m $user_flowise\e[0m"
echo ""

echo -e "\e[33mSenha:\e[97m $pass_flowise\e[0m"
echo ""

read -p "As respostas estão corretas? (Y/N): " confirmacao
if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
    clear
    instalando_msg
    break
else
    clear
    nome_flowise
    preencha_as_info
fi
done

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/3]\e[0m"
echo ""
sleep 3

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• VERIFICANDO/INSTALANDO POSTGRES \e[33m[2/3]\e[0m"
echo ""

verificar_container_postgres
if [ $? -eq 0 ]; then
        echo ""
        criar_banco_postgres_flowise > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1

    else
        ferramenta_postgres > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1
        criar_banco_postgres_flowise > /dev/null 2>&1
fi

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INSTALANDO FLOWISE \e[33m[3/3]\e[0m"
echo ""

encryption_key=$(openssl rand -hex 16)

cat > flowise.yaml <<EOL
version: "3.7"

services:
  flowise:
    image: flowiseai/flowise:latest
    command: flowise start
    networks:
     - $nome_rede_interna
    volumes:
     - flowise_data:/root/.flowise
    environment:
     - FLOWISE_USERNAME=$user_flowise
     - FLOWISE_PASSWORD=$pass_flowise
     - DATABASE_TYPE=postgres
     - DATABASE_HOST=postgres
     - DATABASE_PORT=5432
     - DATABASE_USER=postgres
     - DATABASE_PASSWORD=$senha_postgres
     - DATABASE_NAME=flowise
     - FLOWISE_SECRETKEY_OVERWRITE=$encryption_key
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.flowise.rule=Host(\`$url_flowise\`)
        - traefik.http.services.flowise.loadBalancer.server.port=3000
        - traefik.http.routers.flowise.service=flowise
        - traefik.http.routers.flowise.entrypoints=websecure
        - traefik.http.routers.flowise.tls.certresolver=letsencryptresolver

networks:
  $nome_rede_interna:
    external: true
    name: $nome_rede_interna

volumes:
  flowise_data:
    external: true

EOL

docker stack deploy --prune --resolve-image always -c flowise.yaml flowise  > /dev/null 2>&1

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço flowise está ativo
    if docker service ls --filter "name=flowise" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[Flowise]\e[0m"
echo ""
echo -e "\e[33mDominio:\e[97m https://$url_flowise\e[0m"
echo ""
echo -e "\e[33mUsuario:\e[97m $user_flowise\e[0m"
echo ""
echo -e "\e[33mSenha:\e[97m $pass_flowise\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi

}

ferramenta_pgAdmin_4() {
dados
clear
nome_pgAdmin_4
preencha_as_info

while true; do

echo -e "\e[97mPasso$amarelo 1/3\e[0m"
echo -en "\e[33mDigite o dominio para o PgAdmin 4 (ex: pgadmin.oriondesign.art.br): \e[0m" && read -r url_PgAdmin_4
echo ""

echo -e "\e[97mPasso$amarelo 2/3\e[0m"
echo -en "\e[33mDigite um email para o PgAdmin 4 (ex: contato@oriondesign.art.br): \e[0m" && read -r user_PgAdmin_4
echo ""

echo -e "\e[97mPasso$amarelo 3/3\e[0m"
echo -en "\e[33mDigite uma senha para o usuario (ex: @Senha123_): \e[0m" && read -r pass_PgAdmin_4
echo ""

clear
nome_pgAdmin_4
conferindo_as_info

echo -e "\e[33mDominio do PgAdmin 4\e[97m $url_PgAdmin_4\e[0m"
echo ""

echo -e "\e[33mEmail:\e[97m $user_PgAdmin_4\e[0m"
echo ""

echo -e "\e[33mSenha:\e[97m $pass_PgAdmin_4\e[0m"
echo ""

read -p "As respostas estão corretas? (Y/N): " confirmacao
if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
    clear
    instalando_msg
    break
else
    clear
    nome_pgAdmin_4
    preencha_as_info
fi
done

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/3]\e[0m"
echo ""
sleep 3

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INSTALANDO PGADMIN 4 \e[33m[2/3]\e[0m"
echo ""

cat > pgadmin.yaml <<EOL
version: '3.7'

services:  
  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $user_PgAdmin_4
      PGADMIN_DEFAULT_PASSWORD: '$pass_PgAdmin_4'
    deploy:
      mode: replicated
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      resources:
          limits:
            cpus: '0.4'
            memory: 256M
      labels:
          - traefik.enable=true
          - traefik.http.routers.pgadmin.rule=Host(\`$url_PgAdmin_4\`)
          - traefik.http.services.pgadmin.loadbalancer.server.port=80
          - traefik.http.routers.pgadmin.service=pgadmin
          - traefik.http.routers.pgadmin.tls.certresolver=letsencryptresolver
          - traefik.http.routers.pgadmin.entrypoints=websecure
          - traefik.http.routers.pgadmin.tls=true
    networks:
        - $nome_rede_interna

networks:
  $nome_rede_interna:
    name: $nome_rede_interna
    external: true

volumes:
  pgadmin_data:
    external: true
EOL

docker stack deploy --prune --resolve-image always -c pgadmin.yaml pgadmin  > /dev/null 2>&1

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço pgadmin está ativo
    if docker service ls --filter "name=pgadmin" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[PgAdmin 4]\e[0m"
echo ""
echo -e "\e[33mDominio:\e[97m https://$url_PgAdmin_4\e[0m"
echo ""
echo -e "\e[33mEmail:\e[97m $user_PgAdmin_4\e[0m"
echo ""
echo -e "\e[33mSenha:\e[97m $pass_PgAdmin_4\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi
}

ferramenta_nocobase() {
dados
clear
nome_nocobase
preencha_as_info

while true; do

echo -e "\e[97mPasso$amarelo 1/4\e[0m"
echo -en "\e[33mDigite o dominio para o Nocobase (ex: nocobase.oriondesign.art.br): \e[0m" && read -r url_nocobase
echo ""

echo -e "\e[97mPasso$amarelo 2/4\e[0m"
echo -en "\e[33mDigite um email para o Nocobase (ex: contato@oriondesign.art.br): \e[0m" && read -r mail_nocobase
echo ""

echo -e "\e[97mPasso$amarelo 3/4\e[0m"
echo -en "\e[33mDigite um nome de usuario para o Nocobase (ex: admin): \e[0m" && read -r user_nocobase
echo ""

echo -e "\e[97mPasso$amarelo 4/4\e[0m"
echo -en "\e[33mDigite uma senha para o usuario (ex: @Senha123_): \e[0m" && read -r pass_nocobase
echo ""

clear
nome_nocobase
conferindo_as_info

echo -e "\e[33mDominio do Nocobase:\e[97m $url_nocobase\e[0m"
echo ""

echo -e "\e[33mEmail:\e[97m $mail_nocobase\e[0m"
echo ""

echo -e "\e[33mUsuario:\e[97m $user_nocobase\e[0m"
echo ""

echo -e "\e[33mSenha:\e[97m $pass_nocobase\e[0m"
echo ""

read -p "As respostas estão corretas? (Y/N): " confirmacao
if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
    clear
    instalando_msg
    break
else
    clear
    nome_nocobase
    preencha_as_info
fi
done

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/4]\e[0m"
echo ""
sleep 3

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• VERIFICANDO/INSTALANDO POSTGRES \e[33m[2/4]\e[0m"
echo ""

verificar_container_postgres
if [ $? -eq 0 ]; then
        echo ""
        criar_banco_postgres_nocobase > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1

    else
        ferramenta_postgres > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1
        criar_banco_postgres_nocobase > /dev/null 2>&1
fi

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INSTALANDO NOCOBASE \e[33m[3/4]\e[0m"
echo ""

cat > nocobase.yaml <<EOL
version: "3.7"

services:
  nocobase:
    image: nocobase/nocobase:latest
    volumes:
      - nocobase_storage:/app/nocobase/storage
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=postgres
      - DB_PASSWORD=$senha_postgres
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
      - APP_KEY=$nocobase_key
      - API_BASE_URL=$url_nocobase
      - API_BASE_PATH=/api/
      - PROXY_TARGET_URL=$url_nocobase
      - INIT_ROOT_EMAIL=$mail_nocobase
      - INIT_ROOT_PASSWORD=$pass_nocobase
      - INIT_ROOT_NICKNAME=$user_nocobase
      - INIT_ROOT_USERNAME=$user_nocobase
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.nocobase.rule=Host(\`$url_nocobase\`)
        - traefik.http.services.nocobase.loadbalancer.server.port=80
        - traefik.http.routers.nocobase.service=nocobase
        - traefik.http.routers.nocobase.tls.certresolver=letsencryptresolver
        - traefik.http.routers.nocobase.entrypoints=websecure
        - traefik.http.routers.nocobase.tls=true

    networks:
        - $nome_rede_interna
networks:
  $nome_rede_interna:
    name: $nome_rede_interna
    external: true

volumes:
  nocobase_storage:
    external: true
EOL

docker stack deploy --prune --resolve-image always -c nocobase.yaml nocobase > /dev/null 2>&1

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço nocobase está ativo
    if docker service ls --filter "name=nocobase" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[Nocobase]\e[0m"
echo ""
echo -e "\e[33mDominio:\e[97m https://$url_nocobase\e[0m"
echo ""
echo -e "\e[33mEmail:\e[97m $mail_nocobase\e[0m"
echo ""
echo -e "\e[33mUsuario:\e[97m $user_nocobase\e[0m"
echo ""
echo -e "\e[33mSenha:\e[97m $pass_nocobase\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi
}

ferramenta_botpress() {
dados
clear
nome_botpress
preencha_as_info

while true; do

echo -e "\e[97mPasso$amarelo 1/1\e[0m"
echo -en "\e[33mDigite o dominio para o Botpress (ex: botpress.oriondesign.art.br): \e[0m" && read -r url_botpress
echo ""

clear
nome_botpress
conferindo_as_info

echo -e "\e[33mDominio do Botpress:\e[97m $url_botpress\e[0m"
echo ""

read -p "As respostas estão corretas? (Y/N): " confirmacao
if [ "$confirmacao" = "Y" ] || [ "$confirmacao" = "y" ]; then
    clear
    instalando_msg
    break
else
    clear
    nome_botpress
    preencha_as_info
fi
done

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INICIANDO INSTALAÇÃO \e[33m[1/4]\e[0m"
echo ""
sleep 3

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• VERIFICANDO/INSTALANDO POSTGRES E REDIS \e[33m[2/4]\e[0m"
echo ""

verificar_container_postgres
if [ $? -eq 0 ]; then
        echo ""
        criar_banco_postgres_botpress > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1

    else
        ferramenta_postgres > /dev/null 2>&1
        pegar_senha_postgres > /dev/null 2>&1
        criar_banco_postgres_botpress > /dev/null 2>&1
fi

verificar_container_redis
    if [ $? -eq 0 ]; then
        echo ""
    else
        ferramenta_redis  > /dev/null 2>&1
    fi

#MENSAGEM DE INICIANDO (PASSOS)
echo -e "\e[97m• INSTALANDO BOTPRESS \e[33m[3/4]\e[0m"
echo ""

cat > botpress.yaml <<EOL
version: "3.7"

services:
  botpress:
    image: botpress/server:latest
    volumes:
      - botpress_data:/botpress/data
    environment:
      - EXTERNAL_URL=https://$url_botpress
      - BP_PRODUCTION=true
      - DATABASE_URL=postgresql://postgres:$senha_postgres@postgres:5432/botpress
      - REDIS_URL=redis://redis:6379
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.botpress.rule=Host(\`$url_botpress\`)
        - traefik.http.services.botpress.loadbalancer.server.port=3000
        - traefik.http.routers.botpress.service=botpress
        - traefik.http.routers.botpress.tls.certresolver=letsencryptresolver
        - traefik.http.routers.botpress.entrypoints=websecure
        - traefik.http.routers.botpress.tls=true

    networks:
        - $nome_rede_interna
networks:
  $nome_rede_interna:
    name: $nome_rede_interna
    external: true

volumes:
  botpress_data:
    external: true
EOL

docker stack deploy --prune --resolve-image always -c botpress.yaml botpress > /dev/null 2>&1

#######################################################################
#VERIFICANDO SERVIÇO MENSAGEM
echo -e "\e[97m• VERIFICANDO SERVIÇO\e[0m"
echo ""
while true; do
    # Verifica se o serviço botpress está ativo
    if docker service ls --filter "name=botpress" | grep "1/1"; then
        sleep 10
        break
    fi

    sleep 5
done
#######################################################################

#INSTALAÇÃO FINALIZADA
instalado_msg
guarde_os_dados_msg

echo -e "\e[32m[Botpress]\e[0m"
echo ""
echo -e "\e[33mDominio:\e[97m https://$url_botpress\e[0m"
echo ""

creditos_msg

read -p "Deseja instalar outra aplicação? (Y/N): " choice
    if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then
        return
    else
        cd
        cd
        clear
        exit 1
    fi    
}

ferramenta_remover_stack() {


while true; do
    # Listar as stacks ativas no Docker Swarm com números, excluindo "portainer" e "traefik"
    clear
    nome_remover_stack
    echo "Stacks ativas:"
    echo ""
    docker stack ls --format "table {{.Name}}" | awk 'NR>1 && $1 != "portainer" && $1 != "traefik" {print NR-1". "$0}'
    echo ""
    # Solicitar ao usuário que escolha uma stack para remover ou sair
    read -p "Digite o número da stack que você deseja remover (ou digite '0' para voltar): " user_input

    # Verificar se o usuário deseja sair
    if [ "$user_input" == "0" ]; then
        echo "Saindo do script."
        break
    fi

    # Obter o nome da stack com base no número fornecido
    stack_name=$(docker stack ls --format "{{.Name}}" | sed -n "${user_input}p")

    # Verificar se a stack existe
    if docker stack ps "$stack_name" &> /dev/null; then
        # Remover a stack
        docker stack rm "$stack_name"
        echo "Removendo a stack $stack_name..."
    else
        echo "A stack $stack_name não foi encontrada."
    fi
done

}
#########################
#MENU

while true; do

    nome_menu
    menu_instalador

    read -p "Digite o NÚMERO da opção desejada: " opcao

    case $opcao in
        1)
            ferramenta_traefik_e_portainer
            ;;
        2)
            ferramenta_chatwoot
            ;;
        3)
            ferramenta_evolution
            ;;
        4)
            ferramenta_minio
            ;;
        5)
            ferramenta_typebot
            ;;
        6)
            ferramenta_n8n
            ;;
        7)
            ferramenta_flowise
            ;;
        8)
            ferramenta_pgAdmin_4
            ;;
        9)
            ferramenta_nocobase
            ;;
        10)
            ferramenta_botpress
            ;;
        11)
            
            ;;
        12)
            
            ;;
        13)
            
            ;;
        14)
            
            ;;
        15)
            ferramenta_remover_stack
            ;;
        16)
            echo "Saindo..."
            break
            ;;

        *)

            ;;
    esac
    echo ""
done